[package]
name    = "committable"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
blake3 = { workspace = true }
data-encoding = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0"
