[package]
name = "times"
description = "Time series collector"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
parking_lot = { workspace = true }
tokio = { workspace = true }
# optional:
quanta = { workspace = true, optional = true }
