id = 0
effective_timestamp = "2025-09-01T02:00:00Z"

[[members]]
node = "node_0"
signing_key = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"
dh_key = "AZrLbV37HAGhBWh49JHzup6Wfpu2AAGWGJJnxCDJibiY"
dkg_enc_key = "7PdmfTS45d2hTXB8NcrTmvDwUVBimpYBbrBaGnu3i5Ne65krVfUpbe7bYRHS3AEg7H"
public_address = "127.0.0.1:8000"
http_api = "127.0.0.1:8004"
internal_api = "127.0.0.1:8003"
batch_poster_api = "http://127.0.0.1:8547"

[[members]]
node = "node_1"
signing_key = "vGKKAxVNfkSCdn8qh36nXdSZqyhPq644sQBoeZtcEUCR"
dh_key = "FHTJAk6oyt3jefEp1ZrPEn2MkqRt2LibEFd57AnEUZdb"
dkg_enc_key = "7p1BtEz7WnFMt6Hr28X3Rngqza6i8hRoswhzZRFd6GzgkspLKHBfDocHP8DwzXiNiZ"
public_address = "127.0.0.1:8010"
http_api = "127.0.0.1:8014"
internal_api = "127.0.0.1:8013"
batch_poster_api = "http://127.0.0.1:8557"

[[members]]
node = "node_2"
signing_key = "264jMLf85hfufg4ck97Hw2jiL6i1PHNoGUqxUqfhtssaE"
dh_key = "63eYNKoW2PsWZFhHHj3eZwHTdPE7gEjEDM7gGeDf9Uaj"
dkg_enc_key = "62bnAAbU58zZUcGqy9JKGZRZHkm3g7JZB2DtJGQyChXQBPGvXSS6fF21yoxiVuD1eb"
public_address = "127.0.0.1:8020"
http_api = "127.0.0.1:8024"
internal_api = "127.0.0.1:8023"
batch_poster_api = "http://127.0.0.1:8567"

[[members]]
node = "node_3"
signing_key = "v6UBdLT5BvMhLW7iKv7M2xYeaW2SCAsnZ5PiSg6AaKfA"
dh_key = "Do2GmAexW5MUdD8nToDiBWGbDgk1AwXoxtLTyirDtKQh"
dkg_enc_key = "7aZBFZUEbXxFH9SiGJeUyjzas4mYJ1R13mTPsPeawVU7JFuocfvX9XsRT8qgr17RCe"
public_address = "127.0.0.1:8030"
http_api = "127.0.0.1:8034"
internal_api = "127.0.0.1:8033"
batch_poster_api = "http://127.0.0.1:8577"

[[members]]
node = "node_4"
signing_key = "tV66KknkDH47hRSNzwJtt7Q7EZtxVxQsNnUGoAJdDn6J"
dh_key = "HXaesvEGFiDgrVTix1fKzSLTarFexTZSJD6ymSrF7vPL"
dkg_enc_key = "6R69TzDg3jo1MTex9Uter9XQud458YPpSvXirkYdS295PV81CRvgz5jVWQbkCpZnYV"
public_address = "127.0.0.1:8040"
http_api = "127.0.0.1:8044"
internal_api = "127.0.0.1:8043"
batch_poster_api = "http://127.0.0.1:8587"
