effective_timestamp = "2025-09-01T02:00:00Z"

[[members]]
signing_key = "jAJfgoMcecAgrE8yNPmf1mDP17sVz7b1Fjn4KEx6ETwD"
dh_key = "48sz6ZAGyVZWZsos1Rp6HfzGsFCwVpesKNZjnFp3SGRT"
dkg_enc_key = "7XrX62W3xWEHMpqVR4WRkE8nHCmZ935bkGfhKgNarjTRD46j7bb9oiP3hPQM7AtGBY"
public_address = "127.0.0.1:8000"

[[members]]
signing_key = "oPiEDJTypFsxAStmWDGEDseEPq5PuzKJWHaG23Hs7QZL"
dh_key = "FqQmk1BinZPS8CLnpUFA1b6TcQ11ApZ91miVNaeEp4E8"
dkg_enc_key = "63x7CXWZMm7GsbaU6TtgpihicFeW1uZ1Qhv4gJ78B2Y4GL199RJ1gLACAtN66TNmAb"
public_address = "127.0.0.1:8010"

[[members]]
signing_key = "sfu9yxuAah6nJam1SKrsDATzz2jRyMzyAn3UQDmoRuGB"
dh_key = "5jEpZjdxCPayfSC4pGqqRV3sRrpK1buF886gJFQZ7ttr"
dkg_enc_key = "7THFmRnWqCW4rYhw4KCfcZaJGzpTwgWN1ffgjVGd9Qa6RQ9YYqDwYr8zV2UxtcXrgn"
public_address = "127.0.0.1:8020"

[[members]]
signing_key = "wqzVME8KN7BzQ6JBRMqPG55R88Emevdz56UMkPT12Nnf"
dh_key = "H5NpoSH2qicXMN2Da2xSaVD1tYeS1FPDv8SwiePoBWVR"
dkg_enc_key = "5y5VJiLm9XwKZ7RExBSJ4BZMVpabRLbQA7hgS83XXogiM3fzEzLPqgAPeV7svCgUEY"
public_address = "127.0.0.1:8030"

[[members]]
signing_key = "zNe9THncpgFbudMZsKQkNeP1wSQcGir87h68MdsZq1Ye"
dh_key = "ATcpb6PQhvx3ChpDxY5ZGSjk2zkPeTKSViyNTJnWNntD"
dkg_enc_key = "7QyRTmXVDpNSSqEZ8VDCMeQuadh7RpS5HX74xKhs3YaDjfFqBeCRVR88KDYK1EfgTp"
public_address = "127.0.0.1:8040"
