[net.public]
address = "127.0.0.1:8040"

[net.internal]
address = "127.0.0.1:8043"

[keys.signing]
secret = "9usRZsBVNmDQQ1iGgrGhcB39Fk93rFkQ6c3W2yw5uarv"
public = "zNe9THncpgFbudMZsKQkNeP1wSQcGir87h68MdsZq1Ye"

[keys.dh]
secret = "LXceroxpyRb7LHhHfyMarBNvsvfrjDKSd5Ld34PhyjX"
public = "ATcpb6PQhvx3ChpDxY5ZGSjk2zkPeTKSViyNTJnWNntD"

[keys.dkg]
secret = "HHwwRxEfnHedULaqF3QG2A1joCR1UANYHxLcgrATgBRt"
public = "7QyRTmXVDpNSSqEZ8VDCMeQuadh7RpS5HX74xKhs3YaDjfFqBeCRVR88KDYK1EfgTp"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
