[net]
sailfish_address = "127.0.0.1:8002"
decrypt_address = "127.0.0.1:9002"
certifier_address = "127.0.0.1:10002"
internal_address = "127.0.0.1:11002"

[keys]
signing_key = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"
dh_key = "DRYKr9pHPf6i6QmQiAihrQnEqEYXg96fe5kyMiCrBUJP"
dkg_enc_key = "8sEkWbQe2Ndh79D4Q2ZZALzLXoVSkBpSuwKof8JBtwMBeZVm6ZGd21VrbDP8wAbVkKe"

[chain_config]
parent_chain_id = 31337
parent_chain_rpc_url = "http://127.0.0.1:8545/"
parent_ibox_contr_addr = "0x4dbd4fc535ac27206064b68ffcf827b0a60bab3f"
parent_block_tag = "finalized"
key_manager_contr_addr = "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"

[private]
signing_key = "Fg3tVVbB4UX5cTcqicFkk1ApbUJ71zq9m86ffiBHerTn"
dh_key = "221uwQa7dhYyzwwVQcBF4TAkmyjEcZ5egbrtUN5P3uKq"
dkg_dec_key = "AZzpp7m2d2b2pWgmAVWt6zqgg7pd95tngBsA9LFj4CjrC"
