[net.public]
address = "127.0.0.1:8000"

[net.internal]
address = "127.0.0.1:8003"

[keys.signing]
secret = "FoH2gPCYMJwwKXEgvGNTsrTD7724yJXndgA6gzjjJGpm"
public = "jAJfgoMcecAgrE8yNPmf1mDP17sVz7b1Fjn4KEx6ETwD"

[keys.dh]
secret = "F2bwdVcjPEX2MjXGDGEwcxjp49ZAcyJ31rZLaZhLe6H4"
public = "48sz6ZAGyVZWZsos1Rp6HfzGsFCwVpesKNZjnFp3SGRT"

[keys.dkg]
secret = "HAkeBRT4ogzygFnD4UVULrbMx7fyno4qNShbYwH7C8TF"
public = "7XrX62W3xWEHMpqVR4WRkE8nHCmZ935bkGfhKgNarjTRD46j7bb9oiP3hPQM7AtGBY"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
