[net.public]
address = "127.0.0.1:8002"

[net.internal]
address = "127.0.0.1:11002"

[keys.signing]
secret = "2yWTaC6MWvNva97t81cd9QX5qph68NnB1wRVwAChtuGr"
public = "264jMLf85hfufg4ck97Hw2jiL6i1PHNoGUqxUqfhtssaE"

[keys.dh]
secret = "Fo2nYV4gE9VfoVW9bSySAJ1ZuKT461x6ovZnr3EecCZg"
public = "63eYNKoW2PsWZFhHHj3eZwHTdPE7gEjEDM7gGeDf9Uaj"

[keys.dkg]
secret = "77r7T3En7NNQvRA81G5hLhJD3VpnigJdkPonX3oAwWkX"
public = "62bnAAbU58zZUcGqy9JKGZRZHkm3g7JZB2DtJGQyChXQBPGvXSS6fF21yoxiVuD1eb"

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
