[net.public]
address = "127.0.0.1:8020"

[net.internal]
address = "127.0.0.1:8023"

[keys.signing]
secret = "FjbUDgzriWcXu8eYeKHp42CC8wSwbbkjv9ZWNdxSkgmM"
public = "sfu9yxuAah6nJam1SKrsDATzz2jRyMzyAn3UQDmoRuGB"

[keys.dh]
secret = "8a2vAvyTKENnTYxLmyAnzZTtXyEXL48x2hZRxRBG2zEh"
public = "5jEpZjdxCPayfSC4pGqqRV3sRrpK1buF886gJFQZ7ttr"

[keys.dkg]
secret = "FDXjaRCv4hjQTDKTNcKSn1MXwT7DtBt6SqdDxgd2WQCS"
public = "7THFmRnWqCW4rYhw4KCfcZaJGzpTwgWN1ffgjVGd9Qa6RQ9YYqDwYr8zV2UxtcXrgn"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
