[net.public]
address = "127.0.0.1:8000"

[net.internal]
address = "127.0.0.1:8003"

[keys.signing]
secret = "C8fTG6JZPFVRajV4rSN7oZPCnSAdG3UsFji2tCEXeRWj"
public = "poThxe8T1mSVzWHEeKRQwWGimHRPZpgR1vxi8QnoM3HW"

[keys.dh]
secret = "2iq6LKC5gLpUzoMDtPPDkUhaJFo2XbutaXR2eRrTa9JG"
public = "5hpgYEByvpZKFH65jAHkqYNVrK8SGaa9AkvPaHh1MJBm"

[keys.dkg]
secret = "8JGUfoBxFd2pf1tqxubDdM2StTnLoRHiev4kJVS99FLz"
public = "7c5gxYq7KNSeXrAhwKsA8ZappWLzaQ1kXzBkctx58JnT9EpJ5EFDhWg1ne7gfMaJUe"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
