[net.public]
address = "127.0.0.1:8010"

[net.internal]
address = "127.0.0.1:8013"

[keys.signing]
secret = "Erv5ALswtmZkMadqqpMVwTCEy96xhJFfYcq4FF4JPojT"
public = "m4QcHdpXX4e8qHTw2GCWF965yXpiUwmRjZ7Fn6CJzqEv"

[keys.dh]
secret = "6TqxGQz7ySPdv1GfznbLgPpeHjyk2idzznTYCirffpwc"
public = "AFp9Z4m6HFWYa3vwED4aJcmvbyMTPr8J6uDRoat8HzmT"

[keys.dkg]
secret = "FisBmSTAgEXDo2iHw3bCTyeKFMtXt3zkLztNBLxyMgz8"
public = "7Kp6Bin6pAV7y2LZpS1sS7CUjopksLx2SdbDzEHGUebLFY9WzS6dMGJijXVXzqNMZr"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
