[net.public]
address = "127.0.0.1:8040"

[net.internal]
address = "127.0.0.1:8043"

[keys.signing]
secret = "uV9cQxk1KCY56yU97PTexxaMgbZEb4UN3q4UKz83kss"
public = "coujEMRGJtY7jRGymdmGD5W1MWctJ1e8r4jw5BuX8Mua"

[keys.dh]
secret = "4XnERVerBHdDYH71ehYW5gMmWh3NXPeGaZ5aNvqRJu34"
public = "FAT7vE6EKz8EWrc4kaGMwhvtbE8BVRVwT6t8XoUnx2eh"

[keys.dkg]
secret = "74rSgTXBYK7kvRh9Q7ZzcnsjMjjg9cGv4a3GE4dar1Hf"
public = "5ozY7G3gsA7YeepPk4DUk2RSd4pHTewwohFH7TaCaJB9xTJZMtrkgmkqR6JUwPP9AD"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
