[net.public]
address = "127.0.0.1:8010"

[net.internal]
address = "127.0.0.1:8013"

[keys.signing]
secret = "Bx821rTwZ2vKQfH1H4ABhDAeaeJXH2pShCWfbQcNXKwc"
public = "oPiEDJTypFsxAStmWDGEDseEPq5PuzKJWHaG23Hs7QZL"

[keys.dh]
secret = "6wxEcUm1guuBQLkeXByA2yNgUFDNduFG1aMq6zD7Cb8q"
public = "FqQmk1BinZPS8CLnpUFA1b6TcQ11ApZ91miVNaeEp4E8"

[keys.dkg]
secret = "FpP3u5SdERbEbegS4wtCwKKuXDN22uNKxqraHVHo5K6e"
public = "63x7CXWZMm7GsbaU6TtgpihicFeW1uZ1Qhv4gJ78B2Y4GL199RJ1gLACAtN66TNmAb"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
