[net.public]
address = "127.0.0.1:8020"

[net.internal]
address = "127.0.0.1:8023"

[keys.signing]
secret = "75rKppu6EB7DY7vMHkiJb5dzGstAkcHDcWXV45izcUeW"
public = "2BniRRYZa6kc553V7r8vrDU9DCPqxqpd9Dtts9kqQ41au"

[keys.dh]
secret = "Hsi7APZFGhi1rM1my9RmNWMWMQRqNjQndrPAwjaFDqoy"
public = "Ct5iNL597GbAChFLqKCPB8ovqR5FhBq2ddGRpx2APkFz"

[keys.dkg]
secret = "3XTJHQsUFsxpj4PdDgUR7ewjX6Az71NHy5Dj564Spd6H"
public = "7hG6b4oKJL5peZQnn3NmDrk7Z4Fjq3oHt8Z4gGeRfTtrUJjy2ySXxZ7ZvSWUKfAapo"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
