[net]
sailfish_address = "127.0.0.1:8004"
decrypt_address = "127.0.0.1:9004"
certifier_address = "127.0.0.1:10004"
internal_address = "127.0.0.1:11004"

[keys]
signing_key = "i5ccK9sZFtdWpB6rp4deJKvb8UNMCYhxj7G2sGBAsdam"
dh_key = "6czLW5NW4C74eQUBdzwHGmUzA5B8vbWpuH6amZHXtPnq"
dkg_enc_key = "8t7p3VfTCMXxEAPrcLzMHiANGmEd2Y5aLkKAgrpe5ZyEmgGm2MR1ypweLbCw5RdXySe"

[chain_config]
parent_chain_id = 31337
parent_chain_rpc_url = "http://127.0.0.1:8545/"
parent_ibox_contr_addr = "0x4dbd4fc535ac27206064b68ffcf827b0a60bab3f"
parent_block_tag = "finalized"
key_manager_contr_addr = "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"

[private]
signing_key = "AjaQA4tfSzm8mz7crQNZLzAsa99FXLnLarUX8p65PCUf"
dh_key = "F4TUCvytZyTPVk2qvZAXp9MwWKBEwFMxDeNrTusoTgN1"
dkg_dec_key = "AfrceEeA9DcLh3NYjAk8vrLMdnAA3PbP4Hdr31gW5noan"
