services:
  node0:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "0",
        "--port",
        "8000",
        "--rpc-port",
        "8800",
        "--metrics-port",
        "9000",
        "--base",
        "network"
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.2
    environment:
      - RUST_LOG=timeboost=debug,sailfish=info,timeboost_networking=error
      - TIMEBOOST_PORT=8000
      - TIMEBOOST_RPC_PORT=8800
      - TIMEBOOST_METRICS_PORT=9000
    ports:
      - "8000:8000"
      - "8800:8800"
      - "9000:9000"
  node1:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "1",
        "--port",
        "8001",
        "--rpc-port",
        "8801",
        "--metrics-port",
        "9001",
        "--base",
        "network"
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.3
    environment:
      - RUST_LOG=timeboost=debug,sailfish=info,timeboost_networking=error
      - TIMEBOOST_PORT=8001
      - TIMEBOOST_RPC_PORT=8801
      - TIMEBOOST_METRICS_PORT=9001
    ports:
      - "8001:8001"
      - "8801:8801"
      - "9001:9001"
  node2:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "2",
        "--port",
        "8002",
        "--rpc-port",
        "8802",
        "--metrics-port",
        "9002",
        "--base",
        "network"
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.4
    environment:
      - RUST_LOG=timeboost=debug,sailfish=info,timeboost_networking=error
      - TIMEBOOST_PORT=8002
      - TIMEBOOST_RPC_PORT=8802
      - TIMEBOOST_METRICS_PORT=9002
    ports:
      - "8002:8002"
      - "8802:8802"
      - "9002:9002"
  node3:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "3",
        "--port",
        "8003",
        "--rpc-port",
        "8803",
        "--metrics-port",
        "9003",
        "--base",
        "network"
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.5
    environment:
      - RUST_LOG=timeboost=debug,sailfish=info,timeboost_networking=error
      - TIMEBOOST_PORT=8003
      - TIMEBOOST_RPC_PORT=8803
      - TIMEBOOST_METRICS_PORT=9003
    ports:
      - "8003:8003"
      - "8803:8803"
      - "9003:9003"

  node4:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "4",
        "--port",
        "8004",
        "--rpc-port",
        "8804",
        "--metrics-port",
        "9004",
        "--base",
        "network"
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.6
    environment:
      - RUST_LOG=timeboost=debug,sailfish=info,timeboost_networking=error
      - TIMEBOOST_PORT=8004
      - TIMEBOOST_RPC_PORT=8804
      - TIMEBOOST_METRICS_PORT=9004
    ports:
      - "8004:8004"
      - "8804:8804"
      - "9004:9004"
  tx-generator:
    image: tx-generator:latest
    command: ["/app/tx-generator", "--committee-size", "5", "--docker"]
    depends_on:
      - node0
      - node1
      - node2
      - node3
      - node4
    networks:
      timeboost:
        ipv4_address: 172.20.0.7
    environment:
      - RUST_LOG=debug
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - node0
      - node1
      - node2
      - node3
      - node4
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=timeboost
    networks:
      timeboost:
        ipv4_address: 172.20.0.8
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      timeboost:
        ipv4_address: 172.20.0.9
  fake-contract:
    image: fake-contract:latest
    command: ["uv", "run", "main.py"]
    networks:
      timeboost:
        ipv4_address:
          172.20.0.10

networks:
  timeboost:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  prom_data:
