services:
  node0:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_0.toml",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.2
    environment:
      - RUST_LOG=timeboost=info,sailfish=info,cliquenet=info
      - TIMEBOOST_SAILFISH_PORT=8000
      - TIMEBOOST_DECRYPT_PORT=8001
      - TIMEBOOST_CERTIFIER_PORT=8002
      - TIMEBOOST_RPC_PORT=8800
      - TIMEBOOST_METRICS_PORT=9000
    ports:
      - "8000:8000"
      - "8030:8001"
      - "8060:8002"
      - "8800:8800"
      - "9000:9000"
    depends_on:
      nitro-dev:
        condition: service_healthy
  node1:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_1.toml",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.3
    environment:
      - RUST_LOG=timeboost=info,sailfish=info,cliquenet=info
      - TIMEBOOST_SAILFISH_PORT=8000
      - TIMEBOOST_DECRYPT_PORT=8001
      - TIMEBOOST_CERTIFIER_PORT=8002
      - TIMEBOOST_RPC_PORT=8800
      - TIMEBOOST_METRICS_PORT=9000
    ports:
      - "8001:8000"
      - "8031:8001"
      - "8061:8002"
      - "8801:8800"
      - "9001:9000"
    depends_on:
      nitro-dev:
        condition: service_healthy
  node2:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_2.toml",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.4
    environment:
      - RUST_LOG=timeboost=info,sailfish=info,cliquenet=info
      - TIMEBOOST_SAILFISH_PORT=8000
      - TIMEBOOST_DECRYPT_PORT=8001
      - TIMEBOOST_CERTIFIER_PORT=8002
      - TIMEBOOST_RPC_PORT=8800
      - TIMEBOOST_METRICS_PORT=9000
    ports:
      - "8002:8000"
      - "8032:8001"
      - "8062:8002"
      - "8802:8800"
      - "9002:9000"
    depends_on:
      nitro-dev:
        condition: service_healthy
  node3:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_3.toml",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.5
    environment:
      - RUST_LOG=timeboost=info,sailfish=info,cliquenet=info
      - TIMEBOOST_SAILFISH_PORT=8000
      - TIMEBOOST_DECRYPT_PORT=8001
      - TIMEBOOST_CERTIFIER_PORT=8002
      - TIMEBOOST_RPC_PORT=8800
      - TIMEBOOST_METRICS_PORT=9000
    ports:
      - "8003:8000"
      - "8033:8001"
      - "8063:8002"
      - "8803:8800"
      - "9003:9000"
    depends_on:
      nitro-dev:
        condition: service_healthy
  node4:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_4.toml",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.6
    environment:
      - RUST_LOG=timeboost=info,sailfish=info,cliquenet=info
      - TIMEBOOST_SAILFISH_PORT=8000
      - TIMEBOOST_DECRYPT_PORT=8001
      - TIMEBOOST_CERTIFIER_PORT=8002
      - TIMEBOOST_RPC_PORT=8800
      - TIMEBOOST_METRICS_PORT=9000
    ports:
      - "8004:8000"
      - "8034:8001"
      - "8064:8002"
      - "8804:8800"
      - "9004:9000"
    depends_on:
      nitro-dev:
        condition: service_healthy
  nitro-dev:
    image: offchainlabs/nitro-node:v3.2.1-d81324d
    ports:
      - "8547:8547"
    networks:
      timeboost:
        ipv4_address: 172.20.0.12
    command: --dev --http.addr 0.0.0.0 --http.api=net,web3,eth,debug
    healthcheck:
      test: ["CMD", "curl", "-s", "-X", "POST", "--data", '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}', "-H", "Content-Type: application/json", "http://localhost:8547"]
      interval: 5s
      timeout: 3s
      retries: 10
  yapper:
    image: yapper:latest
    command:
      [
        "/app/yapper",
        "--tps",
        "1",
        "--keyset-file",
        "committee.json",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.13

networks:
  timeboost:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
