version: "3.8"

services:
  node0:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "0",
        "--timeboost-port",
        "8000",
        "--timeboost-rpc-port",
        "8800",
      ]
    networks:
      - timeboost
    environment:
      - RUST_LOG=timeboost=debug,sailfish=debug
      - TIMEBOOST_PORT=8000
      - TIMEBOOST_RPC_PORT=8800
    ports:
      - "8000:8000"
      - "8800:8800"

  node1:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "1",
        "--timeboost-port",
        "8001",
        "--timeboost-rpc-port",
        "8801",
      ]
    networks:
      - timeboost
    environment:
      - RUST_LOG=timeboost=debug,sailfish=debug
      - TIMEBOOST_PORT=8001
      - TIMEBOOST_RPC_PORT=8801
    ports:
      - "8001:8001"
      - "8801:8801"

  node2:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "2",
        "--timeboost-port",
        "8002",
        "--timeboost-rpc-port",
        "8802",
      ]
    networks:
      - timeboost
    environment:
      - RUST_LOG=timeboost=debug,sailfish=debug
      - TIMEBOOST_PORT=8002
      - TIMEBOOST_RPC_PORT=8802
    ports:
      - "8002:8002"
      - "8802:8802"

  node3:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "3",
        "--timeboost-port",
        "8003",
        "--timeboost-rpc-port",
        "8803",
      ]
    networks:
      - timeboost
    environment:
      - RUST_LOG=timeboost=debug,sailfish=debug
      - TIMEBOOST_PORT=8003
      - TIMEBOOST_RPC_PORT=8803
    ports:
      - "8003:8003"
      - "8803:8803"

  node4:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--id",
        "4",
        "--timeboost-port",
        "8004",
        "--timeboost-rpc-port",
        "8804",
      ]
    networks:
      - timeboost
    environment:
      - RUST_LOG=timeboost=debug,sailfish=debug
      - TIMEBOOST_PORT=8004
      - TIMEBOOST_RPC_PORT=8804
    ports:
      - "8004:8004"
      - "8804:8804"

networks:
  timeboost:
    name: timeboost
