services:
  demo-l1-network:
    image: ghcr.io/espressosystems/geth-l1:main
    command: --dev --dev.period=1
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - "./geth-config/genesis-default.json:/genesis.json"
      - "./geth-config/test-jwt-secret.txt:/config/test-jwt-secret.txt"
    networks:
      timeboost:
        ipv4_address: 172.20.0.11
    healthcheck:
      test: ["CMD", "curl", "-s", "-X", "POST", "--data", '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}', "-H", "Content-Type: application/json", "http://localhost:8545"]
      interval: 5s
      timeout: 3s
      retries: 10
  deploy-contract:
    image: timeboost:latest
    environment:
      - RUST_LOG=debug
    entrypoint: [
      "/app/deploy-contract",
      "-d", "/app/deploy",
      "-r", "/app/register",
      "-c", "committee.toml",
      "-u", "http://172.20.0.11:8545"
    ]
    depends_on:
      demo-l1-network:
        condition: service_healthy
    networks:
      - timeboost
  node0:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_0.toml",
        "--https-only", "false",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.2
    environment:
      - RUST_LOG=timeboost=info,sailfish=warn,cliquenet=warn,timeboost-builder=debug,robusta=info,block_checker=info
    ports:
      - "8000:8000"
      - "8030:8001"
      - "8060:8002"
      - "8080:8003"
      - "8100:8004"
      - "8800:8800"
      - "9000:9000"
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
  node1:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_1.toml",
        "--https-only", "false",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.3
    environment:
      - RUST_LOG=timeboost=info,sailfish=warn,cliquenet=warn,timeboost-builder=debug,robusta=info,block_checker=info
    ports:
      - "8001:8000"
      - "8031:8001"
      - "8061:8002"
      - "8081:8003"
      - "8101:8004"
      - "8801:8800"
      - "9001:9000"
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
  node2:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_2.toml",
        "--https-only", "false",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.4
    environment:
      - RUST_LOG=timeboost=info,sailfish=warn,cliquenet=warn,timeboost-builder=debug,robusta=info,block_checker=info
    ports:
      - "8002:8000"
      - "8032:8001"
      - "8062:8002"
      - "8082:8003"
      - "8102:8004"
      - "8802:8800"
      - "9002:9000"
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
  node3:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_3.toml",
        "--https-only", "false",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.5
    environment:
      - RUST_LOG=timeboost=info,sailfish=warn,cliquenet=warn,timeboost-builder=debug,robusta=info,block_checker=info
    ports:
      - "8003:8000"
      - "8033:8001"
      - "8063:8002"
      - "8083:8003"
      - "8103:8004"
      - "8803:8800"
      - "9003:9000"
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
  node4:
    image: timeboost:latest
    command:
      [
        "/app/timeboost",
        "--committee-id", "0",
        "--config", "node_4.toml",
        "--https-only", "false",
      ]
    networks:
      timeboost:
        ipv4_address: 172.20.0.6
    environment:
      - RUST_LOG=timeboost=info,sailfish=warn,cliquenet=warn,timeboost-builder=warn,robusta=info,block_checker=info
    ports:
      - "8004:8000"
      - "8034:8001"
      - "8064:8002"
      - "8084:8003"
      - "8104:8004"
      - "8804:8800"
      - "9004:9000"
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
  block-maker:
    image: timeboost:latest
    ports:
      - "55000:55000"
    command:
      [
        "/app/block-maker",
        "--port", "55000",
        "--committee", "committee.toml",
      ]
    environment:
      - RUST_LOG=info
    networks:
      timeboost:
        ipv4_address: 172.20.0.12
  block-checker:
    image: timeboost:latest
    command:
      [
        "/app/block-checker",
        "--config", "node_0.toml",
        "--committee", "committee.toml",
        "--committee-id", "0",
        "--blocks", "10000",
        "--https-only", "false",
      ]
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=trace
    networks:
      timeboost:
        ipv4_address: 172.20.0.15
    depends_on:
      deploy-contract:
        condition: service_completed_successfully
  yapper:
    image: timeboost:latest
    command:
      [
        "/app/yapper",
        "--keyset-file", "committee.toml",
      ]
    environment:
      - RUST_LOG=info
    networks:
      timeboost:
        ipv4_address: 172.20.0.13
  espresso-dev-node:
    pid: host
    image: ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node:latest
    ports:
      - "41000:41000"
      - "41003:41003"
      - "20000:20000"
    environment:
      - ESPRESSO_BUILDER_PORT=41003
      - ESPRESSO_DEPLOYER_ACCOUNT_INDEX=5
      - ESPRESSO_DEV_NODE_PORT=20000
      - ESPRESSO_SEQUENCER_API_PORT=41000
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC=indoor dish desk flag debris potato excuse depart ticket judge file exit
      - ESPRESSO_SEQUENCER_L1_PROVIDER=http://172.20.0.11:8545
      - ESPRESSO_SEQUENCER_DATABASE_MAX_CONNECTIONS=25
      - ESPRESSO_DEV_NODE_EPOCH_HEIGHT=1000000
      - ESPRESSO_DEV_NODE_MAX_BLOCK_SIZE=10485760
      - ESPRESSO_SEQUENCER_STORAGE_PATH=/data/espresso
      - RUST_LOG=INFO
      - RUST_LOG_FORMAT
      - ESPRESSO_DEV_NODE_VERSION=0.4
    volumes:
      - espresso_storage:/data/espresso
    depends_on:
      demo-l1-network:
        condition: service_healthy
    networks:
      timeboost:
        ipv4_address: 172.20.0.14
networks:
  timeboost:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  espresso_storage:
