[project]
name = "timeboost"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.6",
    "ruff>=0.9.2",
    "typer>=0.15.1",
    "uvicorn>=0.34.0",
]
