[nat]
device = "enp5s0"
cidr   = "11.0.0.0/8"

[bridge]
name = "bridge"
cidr = "11.0.1.0/16"

[[device]]
node   = "node_0"
name   = "dev0"
cidr   = "11.0.0.1/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_1"
name   = "dev1"
cidr   = "11.0.0.10/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_2"
name   = "dev2"
cidr   = "11.0.0.20/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_3"
name   = "dev3"
cidr   = "11.0.0.30/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_4"
name   = "dev4"
cidr   = "11.0.0.40/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_5"
name   = "dev5"
cidr   = "11.0.0.50/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_6"
name   = "dev6"
cidr   = "11.0.0.60/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_7"
name   = "dev7"
cidr   = "11.0.0.70/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_8"
name   = "dev8"
cidr   = "11.0.0.80/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_9"
name   = "dev9"
cidr   = "11.0.0.90/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_10"
name   = "dev10"
cidr   = "11.0.0.100/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_11"
name   = "dev11"
cidr   = "11.0.0.110/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_12"
name   = "dev12"
cidr   = "11.0.0.120/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_13"
name   = "dev13"
cidr   = "11.0.0.130/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_14"
name   = "dev14"
cidr   = "11.0.0.140/16"
delay  = "10ms"
#jitter = "2ms"
