[nat]
device = "eth0"
cidr = "11.0.0.0/8"

[bridge]
name = "bridge"
cidr = "11.0.1.0/16"

[[device]]
node = "node_0"
name = "dev1"
cidr = "11.0.0.1/16"
delay = "50ms"
jitter = "50ms"

[[device]]
node = "node_1"
name = "dev2"
cidr = "11.0.0.2/16"
delay = "50ms"
jitter = "50ms"

[[device]]
node = "node_2"
name = "dev3"
cidr = "11.0.0.3/16"
delay = "50ms"
jitter = "50ms"

[[device]]
node = "node_3"
name = "dev4"
cidr = "11.0.0.4/16"
delay = "50ms"
jitter = "50ms"

[[device]]
node = "node_4"
name = "dev5"
cidr = "11.0.0.5/16"
delay = "50ms"
jitter = "50ms"
