[nat]
device = "eth0"
cidr   = "11.0.0.0/8"

[bridge]
name = "bridge"
cidr = "11.0.1.0/16"

[[device]]
node   = "node_0"
name   = "dev0"
cidr   = "11.0.0.1/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_1"
name   = "dev1"
cidr   = "11.0.0.2/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_2"
name   = "dev2"
cidr   = "11.0.0.3/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_3"
name   = "dev3"
cidr   = "11.0.0.4/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_4"
name   = "dev4"
cidr   = "11.0.0.5/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_5"
name   = "dev5"
cidr   = "11.0.0.6/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_6"
name   = "dev6"
cidr   = "11.0.0.7/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_7"
name   = "dev7"
cidr   = "11.0.0.8/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_8"
name   = "dev8"
cidr   = "11.0.0.9/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_9"
name   = "dev9"
cidr   = "11.0.0.10/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_10"
name   = "dev10"
cidr   = "11.0.0.11/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_11"
name   = "dev11"
cidr   = "11.0.0.12/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_12"
name   = "dev12"
cidr   = "11.0.0.13/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_13"
name   = "dev13"
cidr   = "11.0.0.14/16"
delay  = "10ms"
#jitter = "2ms"

[[device]]
node   = "node_14"
name   = "dev14"
cidr   = "11.0.0.15/16"
delay  = "10ms"
#jitter = "2ms"
