committee = 0
stamp = "/tmp/timeboost.9.stamp"

[net.public]
address = "11.0.0.10:8000"
http-api = "11.0.0.10:8004"

[net.internal]
address = "11.0.0.10:8003"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "4yhZYmNvAouKFpiYomrV9aH8kUZTLRH2hiCZtJzcAASa"
public = "28NkSnRnefwgwoP5Xj1Xo21bAHpVQcYEYouTNyjyjH5V3"

[keys.dh]
secret = "Bk2wY7o2YE9gpu6jxiRSbWiMU88H8s9D9MQGMaF2LJ7h"
public = "69BWDWEuKYvsF9EfCjDYJpxrNpSymvX23o3JHxQxhVfQ"

[keys.dkg]
secret = "8xJy9zbrnPbTxCsoq3e78GSRCqi2SbYGAimkAPeZhxvE"
public = "7jUogxWxRhXuaRsfPcA3g8eLbLCu5MgJBW66qz8oi4dvy6zm9aewDDK1HgNMqSuGXE"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
ws-url = "ws://11.0.1.0:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
