committee = 0
stamp = "/tmp/timeboost.0.stamp"

[net.public]
address = "11.0.0.1:8000"
http-api = "11.0.0.1:8004"

[net.internal]
address = "11.0.0.1:8003"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "4HzC6SoCS2xiyEgo5kNLGXaHCPi6Ln9SgwVKEDdBmPh7"
public = "gReCjvFM7ZDMLekRgDBtFQgZ3ogKk3EgvSZBGCq9hnWH"

[keys.dh]
secret = "6QDhRkzHNQqdiWnXAEdEPdVhMPRRb82gTeyBEWCAhqxa"
public = "7deaKLRjRLYi6gCcywgzwS59NwfMk7kkERsMKdcu6dwz"

[keys.dkg]
secret = "D8FzmkVKDC5Sky4BkDBS8G2Uiwd1Wj8n19GGMhsFDKkc"
public = "7ojQP6jCiNBSGb8AXMuscWTPUupcdAHH84FcoPpsM7waZoqkYU7pXPebQrwcxNNxXx"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
ws-url = "ws://11.0.1.0:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
