committee = 0
stamp = "/tmp/timeboost.4.stamp"

[net.public]
address = "11.0.0.5:8000"
http-api = "11.0.0.5:8004"

[net.internal]
address = "11.0.0.5:8003"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "7uaKezj4YvDwGzc8XkLaeMWxERsqviwU6YZCoJYLMJ21"
public = "2AbS1dXhEXojDzoxMeR65cKi2aVuctmoueT7kJhKatSzo"

[keys.dh]
secret = "DK6ZRToukf8cGhjvtVmACUzZBNXFK98wjHNBH3tdC18T"
public = "8FUF9ZkDPgb835yWq7DpkLLvmJhroR4QWndqZPzYvneE"

[keys.dkg]
secret = "D6YpfP6vRS4jRM92o1bCC1d1ihTacok8LFHTL73P9N2s"
public = "78CtjmmRqNuH1w1wbMZfMExM64Q5G1wNUoAXD82ShiPYDuoP9JxehhNYYAjLVJnG62"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
ws-url = "ws://11.0.1.0:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
