committee = 0
stamp = "/tmp/timeboost.11.stamp"

[net.public]
address = "11.0.0.12:8000"
http-api = "11.0.0.12:8004"
batch-poster-api = "11.0.0.12:8547"

[net.internal]
address = "11.0.0.12:8003"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "FL84xojYc59vAMuKibGA797nvFgCp7uRZfgx3GZN5PK4"
public = "iNJBiPwwdA53Gds2rnJnSm1sjvnR8Ep72LZKf8fxVo2e"

[keys.dh]
secret = "BWqUqoQPHgBwQ782YHyJAsvJDAxwTBs6EskCEDmrffuT"
public = "D2dCHzbNYVo18z9yH4KnuiRbGMj3qxxRLAGwFEUrBUM3"

[keys.dkg]
secret = "G61nMJVtyHeSDFqNSYeVQUDGr71Y5K2uqrdFBjZYEZvG"
public = "6EGHKHhBh984R4CV9F7g7oHDvQrFisoAk8onZqUnUj1UwQd38hzVxgVZRW7n4aDCdo"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
ws-url = "ws://11.0.1.0:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
