committee = 0
stamp = "/tmp/timeboost.1.stamp"

[net.public]
address = "11.0.0.2:8000"
http-api = "11.0.0.2:8004"

[net.internal]
address = "11.0.0.2:8003"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "5k1LqAjBMzAbEjW5xARYZSyDHhDXTvZBr1BXxTjyW99g"
public = "evyKrgKBPePY5KGbUbn8WhT9w1pq8R8AjG8jLrgo6Jpk"

[keys.dh]
secret = "4xna8mFRT6EAXAgV2UxA2ACnkTmqLTRfso2LCe64RNTh"
public = "7pFKtftteAdTaDEkCq6SKzcrMXWD4rcZ3phrg1ouYygB"

[keys.dkg]
secret = "ek9Vr2scVZNDoTZ9W4TNxiyvcZbSCo8dJsTVqcG6an6"
public = "6SaKBeNyQVAQ4m93qW8eSXAq36RgidJ35a6Xa6JTmsu1vyFSoKqNFKQxY5MWwQNH2K"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
ws-url = "ws://11.0.1.0:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
