committee = 0
stamp = "/tmp/timeboost.8.stamp"

[net.public]
address = "11.0.0.9:8000"
http-api = "11.0.0.9:8004"

[net.internal]
address = "11.0.0.9:8003"
nitro = "11.0.1.0:55000"

[keys.signing]
secret = "5mLCMSVT4f8HPqCqdKChxugpMcQ3x1C7hwfEnsTApFfp"
public = "fkTFXcMaEEzutGCreYpDb1B2h8hNMf6UMNRbt8dnhi2v"

[keys.dh]
secret = "2PojAT3g5iqGTrgLhTRKKHqwbeoFhRkzkYLM9AttFoKK"
public = "vzvao6vfQtWpBJvPsVCk9FL7RsJBNE4W8SvNWtofxqB"

[keys.dkg]
secret = "ELWc3w8nMP2Cou2Ak8SKmjzZ1MWrJLAsEuGLf89voF5T"
public = "5zhvUH7JXkViZ6FTRocX6TTUbC83x7n9cAkL8TeNi8cuMazhTESU4QvGQJrunbzwgd"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://11.0.1.0:8545/"
ws-url = "ws://11.0.1.0:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
builder-base-url = "https://builder.decaf.testnet.espresso.network/v0/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
