[wallet]
mnemonic = "test test test test test test test test test test test junk"
account_index = 0

[deployments]
chain_url = "http://127.0.0.1:8545" # replace with the RPC endpoint of the target chain
key_manager = "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
