format:
    terraform fmt

check:
    terraform validate

plan:
    terraform plan

allocate-ips num:
    terraform apply -target=aws_eip.allocated_ips

apply *args: check
    terraform apply {{args}}
