[package]
name = "timeboost-core"
version.workspace = true
edition.workspace = true
description.workspace = true

[features]
test = []

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
committable = { workspace = true }
crossbeam-queue = { workspace = true }
dyn-clone = { workspace = true }
primitive-types = { workspace = true }
futures = { workspace = true }
hotshot-types = { workspace = true }
parking_lot = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
surf-disco = { workspace = true }
thiserror = { workspace = true }
tide-disco = { workspace = true }
timeboost-networking = { path = "../timeboost-networking" }
timeboost-util = { path = "../timeboost-util" }
timeboost-crypto = { path = "../timeboost-crypto" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
quickcheck = "1"
