[package]
name = "timeboost-core"
version.workspace = true
edition.workspace = true
description.workspace = true

[features]
test = []

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
committable = { workspace = true }
crossbeam-queue = { workspace = true }
ethereum-types = { workspace = true }
futures = { workspace = true }
hotshot = { workspace = true }
hotshot-types = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
prometheus = { workspace = true }
tide-disco = { workspace = true }
itertools = "0.12.1"
timeboost-networking = { path = "../timeboost-networking" }
timeboost-util = { path = "../timeboost-util" }


[dev-dependencies]
quickcheck = "1"
