[package]
name = "timeboost-core"
version.workspace = true
edition.workspace = true
description.workspace = true

[features]
default = []
timeboost-testing = []

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
committable = { workspace = true }
ethereum-types = { workspace = true }
hotshot = { workspace = true }
hotshot-types = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
prometheus = "0.13"
itertools = "0.12.1"


[dev-dependencies]
quickcheck = "1"
