[package]
name = "timeboost-core"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
committable = { workspace = true }
ethereum-types = { workspace = true }
hotshot = { workspace = true }
hotshot-types = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
