[package]
name = "timeboost-core"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
