global:
  scrape_interval: 15s

scrape_configs:
- job_name: status
  static_configs:
    - targets:
      - 127.20.0.2:9000
      - 127.20.0.3:9001
      - 127.20.0.4:9002
      - 127.20.0.5:9003
      - 127.20.0.6:9004
  metrics_path: /v0/status/metrics
