{
 "title": "Local Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Committed Round",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "committed_round", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Round Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(round_duration_sum[$__rate_interval]) / rate(round_duration_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RBC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Delivery duration (sec)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(le) (delivery_duration_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACK duration (sec)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(le) (ack_duration_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Established connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "connections", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "RTT .90-quantile (milliseconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(latency_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RTT .95-quantile (milliseconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RTT .5-quantiles (milliseconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RTT .75-quantile (milliseconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(latency_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Latency (RTT - milliseconds)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(le) (latency_bucket)", "legendFormat": "{{le}}" }
   ]
  }
 ]
}