effective_timestamp = "2025-09-01T02:00:00Z"

[[members]]
signing_key = "cjRBQqKWiCmwmmSN5AvWACJ2pSvrCfPg7GAA6GJKVZ8y"
dh_key = "HxzNYceQLYzfeDUA1ogB9EY4RWzyJwEiFrNU7HQwBpdG"
dkg_enc_key = "79GjMuxfaTBbwEBhqTxGZ8PcVw4UJvmC514aBiiVxkFq9ctUXGbmuV9A87i9e5fKe6"
public_address = "127.0.0.1:8000"

[[members]]
signing_key = "vqa8EqiusUHGU5XNVM3og4qjUiUbptYTT6JsBXhU7tqn"
dh_key = "CXp3hFF2xoP6ERFKd6tt1rWgfpnceK62au6qiB5uguqh"
dkg_enc_key = "7jZYT4XVyDZLqtsBBntP2qhtjaXouRscBKyzfpZCbBYfcGLQCM8uVLHc26vqH6mKrV"
public_address = "127.0.0.1:8010"
