effective_timestamp = "2025-09-01T02:00:00Z"

[[members]]
signing_key = "nYhHM4sfiXoxEcmGV8gTgzQZdHEE5HDbSt6LgUsHs1G1"
dh_key = "Eupnv1J67fdfZpZDAFxNbWJ3Y5wWtCZcrFtLd6PuPhAJ"
dkg_enc_key = "5rC3hWqnZSnn568NupfqqkxvLempdzq6z5fDUHVSkZV5mxv2GPRvYaG7JPWkYrNSoB"
public_address = "127.0.0.1:8000"

[[members]]
signing_key = "wnLCGaDSQrhUVDvffXCAZUfL2uJ3uwNkVnzRyvwAwKSg"
dh_key = "CeWS52bRwVLDfJq4hk4yRTFvX2uuJw494Bs7umfmiM4G"
dkg_enc_key = "6azqwkVDns6ufoJeBfapKhdiMq496o4vE4YrJjLXG1AVc6KfxWETGiL1dJvhbZRRtU"
public_address = "127.0.0.1:8010"
