effective_timestamp = "2025-09-01T10:00:00Z"

[[members]]
signing_key = "hksYV9N4q2omdJF6V8KrZN79tat8mZjiQhYufxtPZTn2"
dh_key = "99oupN2AzSf9t9GQnxfojE3AhvpoXyHBe2BduUchwjMW"
dkg_enc_key = "5xSQ6SwsMZ1Q5zswRuFnAQWBmXpc8ii5ZL5hkK5hURQ3scv7hnDgnE4sATcjpagsxx"
public_address = "127.0.0.1:8000"

[[members]]
signing_key = "rK8pn4Mnn7iUf4ML8R3bU7trmqed8APavxfCy3tFi3fM"
dh_key = "Hb1sbBQ8yDEcNqfAAcw6V5FhGRu679vhy29KpMdMApSk"
dkg_enc_key = "6cAcEvWVUukpR8Y4y82FLagbLKP5YLhVqTdEcjwJYoBLrzJK2zxPg8b33AjYzrW3Dn"
public_address = "127.0.0.1:8010"
