[net.public]
address = "127.0.0.1:8010"

[net.internal]
address = "127.0.0.1:8013"
nitro = "localhost:55001"

[keys.signing]
secret = "7ibRK7tpVEz2u53USzYktgEq3rVv2hxTnc67CAvABXYE"
public = "bsRbe3znv9uJEbbz247P6JgcAFtDxuZ1ypo4eumMNhQ1"

[keys.dh]
secret = "863TFM5TvYhXDo7M9ppZ6y71Yue7cXeiJkAxdGzSJeAo"
public = "BZdQ7CoKmHKrHoRg44AV9viHaYh75A4LTQZZDFpr7s74"

[keys.dkg]
secret = "VaDdw7YDD3wyn6ARsCprrGU56NCt6kf2zb4qR2NGi6D"
public = "7631hsR1bDskt7UNnYrVPFaAr8NXPjLj6grCHgNjAC8hRVLe1otKK4NZC2XkGvrqqJ"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
