[net.public]
address = "127.0.0.1:8000"

[net.internal]
address = "0.0.0.0:8003"
nitro = "localhost:55000"

[keys.signing]
secret = "2JNW8EDy4G4nfAV8y5is6uL7n2jFvcSSgemMMBNunWnJ"
public = "cjRBQqKWiCmwmmSN5AvWACJ2pSvrCfPg7GAA6GJKVZ8y"

[keys.dh]
secret = "F6iNXHPqceZQBdujbed1UtwuA8onXyXsHwYiJpsgNmid"
public = "HxzNYceQLYzfeDUA1ogB9EY4RWzyJwEiFrNU7HQwBpdG"

[keys.dkg]
secret = "67HMbuGrF3kxEGRQAUmu34UnrG2P3vDKUeJ3fyhqaRuM"
public = "79GjMuxfaTBbwEBhqTxGZ8PcVw4UJvmC514aBiiVxkFq9ctUXGbmuV9A87i9e5fKe6"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
