[net.public]
address = "127.0.0.1:8000"

[net.internal]
address = "127.0.0.1:8003"
nitro = "localhost:55000"

[keys.signing]
secret = "4ZgAktx4bNaoueLrqexWQVrcxcirAH5cRDJregrLvWsd"
public = "26pFBXZBuRPhXfhYkbJE9RdtQyKRUue1yombzb7GBBPne"

[keys.dh]
secret = "obGuCJ3X5zqvii8CCqh25AX2fFM8GViDnZCBP43pPr2"
public = "Hz1ho2J1PCE7HnSQWA9iN91PFx6e53pWGByPxRHxWCFv"

[keys.dkg]
secret = "HbGD6eMF1ZHSLBHZLaF296RneBYJJfSn68iqeWNMtRDw"
public = "5mnuf3nx4io18zk4PTLLu7ee2XukLJWMetADPktQCyxbeN3jGG5rNojc1aFBqrbe5S"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
