[net.public]
address = "127.0.0.1:8000"

[net.internal]
address = "127.0.0.1:8003"
nitro = "localhost:55000"

[keys.signing]
secret = "3Sci1zoohXzPaXPFvMNDEEWyZAgPy2nZYtx45y6FKEVS"
public = "nYhHM4sfiXoxEcmGV8gTgzQZdHEE5HDbSt6LgUsHs1G1"

[keys.dh]
secret = "4PaujicUtdVDtEjNSwKkDWfHrN1zokDftxTw8x9JZLyv"
public = "Eupnv1J67fdfZpZDAFxNbWJ3Y5wWtCZcrFtLd6PuPhAJ"

[keys.dkg]
secret = "J7oMfDZNoeWq5YRMUFboK1FmiYYfkn4Um5TQTtfVWaML"
public = "5rC3hWqnZSnn568NupfqqkxvLempdzq6z5fDUHVSkZV5mxv2GPRvYaG7JPWkYrNSoB"

[chain]
namespace = 10101

[chain.parent]
id = 1337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
