[net.public]
address = "127.0.0.1:8010"

[net.internal]
address = "127.0.0.1:8013"
nitro = "localhost:55010"

[keys.signing]
secret = "9ik7Z5kJ4VVRzbTs8ydAaKno7SHUK9bPWfZpi2h8zRkS"
public = "rK8pn4Mnn7iUf4ML8R3bU7trmqed8APavxfCy3tFi3fM"

[keys.dh]
secret = "2WDaWtVsoD7ymfHRFEwwfA7JznX75eRtSitXXWJD8pJt"
public = "Hb1sbBQ8yDEcNqfAAcw6V5FhGRu679vhy29KpMdMApSk"

[keys.dkg]
secret = "BwVBMnRvJ9YMjkqf521G5fjA4RUT7GQCPVkZaYvbo68Q"
public = "6cAcEvWVUukpR8Y4y82FLagbLKP5YLhVqTdEcjwJYoBLrzJK2zxPg8b33AjYzrW3Dn"

[chain]
namespace = 10101

[chain.parent]
id = 1337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
