[net.public]
address = "127.0.0.1:8010"

[net.internal]
address = "0.0.0.0:8013"
nitro = "localhost:55010"

[keys.signing]
secret = "2NQoXsjfW9QbBWTb1zQwKAwTi2cx97imPngnE4ZuyCSJ"
public = "vqa8EqiusUHGU5XNVM3og4qjUiUbptYTT6JsBXhU7tqn"

[keys.dh]
secret = "B1As9xWQPUsXiJj9SPoceHJrjFQ3ZEHesMFpUwSxstZa"
public = "CXp3hFF2xoP6ERFKd6tt1rWgfpnceK62au6qiB5uguqh"

[keys.dkg]
secret = "39xTDJp6nyNZjApGT8QZP7kCaJRDtLBtTmubZ3p2HgLT"
public = "7jZYT4XVyDZLqtsBBntP2qhtjaXouRscBKyzfpZCbBYfcGLQCM8uVLHc26vqH6mKrV"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
