[net.public]
address = "127.0.0.1:8010"

[net.internal]
address = "127.0.0.1:8013"
nitro = "localhost:55001"

[keys.signing]
secret = "3hPrh6EPTc1u4N1gzoLo7nRsHNqEyZXS6HJgCDTEKq7Y"
public = "wnLCGaDSQrhUVDvffXCAZUfL2uJ3uwNkVnzRyvwAwKSg"

[keys.dh]
secret = "6KXBK48uCdgkAQ4RvmDbRCSNpM6xT6Kyk8heKe6kczk4"
public = "CeWS52bRwVLDfJq4hk4yRTFvX2uuJw494Bs7umfmiM4G"

[keys.dkg]
secret = "35mnm8hTCDqAdKDhASckc9bhHHjHGqWCpRWXsyVmudge"
public = "6azqwkVDns6ufoJeBfapKhdiMq496o4vE4YrJjLXG1AVc6KfxWETGiL1dJvhbZRRtU"

[chain]
namespace = 10101

[chain.parent]
id = 1337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
