[net.public]
address = "127.0.0.1:8000"

[net.internal]
address = "127.0.0.1:8003"
nitro = "localhost:55000"

[keys.signing]
secret = "3LDXngc5tvCJ2psBunSFfUrdJdPYtNX8REPKzGgrA35b"
public = "hksYV9N4q2omdJF6V8KrZN79tat8mZjiQhYufxtPZTn2"

[keys.dh]
secret = "2Hems6dsyRj3XmKjBiqE2PnsKETcnQ4FWhdDanz1x5Ec"
public = "99oupN2AzSf9t9GQnxfojE3AhvpoXyHBe2BduUchwjMW"

[keys.dkg]
secret = "62oVNuZ6wndbFYiTpzdTYnL6GLgTTN8AJjRbcBqyiGmC"
public = "5xSQ6SwsMZ1Q5zswRuFnAQWBmXpc8ii5ZL5hkK5hURQ3scv7hnDgnE4sATcjpagsxx"

[chain]
namespace = 10101

[chain.parent]
id = 1337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
