[meta]
NAME = "timeboost submit api"
DESCRIPTION = "Submit transactions to Timeboost"
FORMAT_VERSION = "0.1.0"

[route.submit]
PATH = ["/submit"]
METHOD = "POST"
DOC = "Submit transaction to Timeboost"

[route.healthz]
PATH = ["/healthz"]
METHOD = "GET"
DOC = "Healthcheck"
