[meta]
NAME = "timeboost submit api"
DESCRIPTION = "Submit transactions to Timeboost"
FORMAT_VERSION = "0.1.0"

[route.submit-priority]
PATH = ["/submit-priority"]
METHOD = "POST"
DOC = "Submit priority bundle to Timeboost"

[route.submit-regular]
PATH = ["/submit-regular"]
METHOD = "POST"
DOC = "Submit regular bundle to Timeboost"

# Returns Some(None) if not ready, Some(key) when ready
[route.enckey]
PATH = ["/enckey"]
METHOD = "POST"
DOC = "Encryption key for threshold decryptable bundle"

[route.healthz]
PATH = ["/healthz"]
METHOD = "GET"
DOC = "Healthcheck"
