[meta]
NAME = "timeboost submit api"
DESCRIPTION = "Submit transactions to Timeboost"
FORMAT_VERSION = "0.1.0"

[route.post_submit]
PATH = ["/submit"]
METHOD = "POST"
DOC = "Submit transaction to Timeboost"

[route.get_metrics]
PATH = ["/metrics"]
METHOD = "GET"
DOC = "Get metrics from Timeboost"
