stamp = "/tmp/timeboost.2.stamp"

[net.public]
address = "127.0.0.1:9020"
http_api = "127.0.0.1:9024"

[net.internal]
address = "127.0.0.1:9023"

[keys.signing]
secret = "9j28e6HiGxdShGwNLH2emYXVaE7mNdBmhikyknSdtTqS"
public = "c24KQW7jK7d8NdKYatGn6cZDSoMro5XsxKoBkkLmSUwN"

[keys.dh]
secret = "7ecZnC9dPzs9pZ6uqCSkEiLr44GqdFgoWCqG5jgD6mJ8"
public = "Fer6ptfw1MgBDxCuLn54Xo7V62iEhZZyQ3JTfyyGMgM9"

[keys.dkg]
secret = "FwzsYVwZRnFMNs11bbMKoVdeQPmMM24dSobxFrscmWnu"
public = "5vacdPGGmQSfS474Fy5dizxoE1GHLW4W48FBx7UfVTtERjtPhFN7CEBT23y6uBHiew"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ws_url = "ws://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base_url = "https://query.decaf.testnet.espresso.network/v1/"
websockets_base_url = "wss://query.decaf.testnet.espresso.network/v1/"
