[package]
name = "multisig"
version = "0.1.0"
description = "Signature set over ED25519 signatures"
edition.workspace = true

[features]
benchmark = []

[dependencies]
bimap = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
committable = { workspace = true }
data-encoding = { workspace = true }
ed25519-compact = { workspace = true }
either = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
thiserror = { workspace = true }
