[package]
name = "yapper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
cliquenet = { path = "../cliquenet" }
reqwest = { workspace = true }
timeboost = { path = "../timeboost" }
timeboost-crypto = { path = "../timeboost-crypto" }
timeboost-utils = { path = "../timeboost-utils" }
tracing = { workspace = true }
tokio = { workspace = true }
