effective_timestamp = 1756181061

[[members]]
signing_key = "eiwaGN1NNaQdbnR9FsjKzUeLghQZsTLPjiL4RcQgfLoX"
dh_key = "AZrLbV37HAGhBWh49JHzup6Wfpu2AAGWGJJnxCDJibiY"
dkg_enc_key = "8t9PdQ61NwF9n7RU1du43C95ndSs6jn2EM7gRCfutVo2YXh6dyXAJiEWhpfYtPUv9gK"
sailfish_address = "172.20.0.2:8000"

[[members]]
signing_key = "23as9Uo6W2AeGronB6nMpcbs8Nxo6CoJ769uePw9sf6Ud"
dh_key = "3V1LzAgCwubtAb1MT1YgTH2scXg6d2bQEhhsAMeyNo6X"
dkg_enc_key = "8rokdkmSKkupd7C9oPd3MBPuBANq6ZaQ7hA1uvoFeLmXanMK7ndXwVCy5vUTPkULA7G"
sailfish_address = "172.20.0.3:8000"

[[members]]
signing_key = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"
dh_key = "DRYKr9pHPf6i6QmQiAihrQnEqEYXg96fe5kyMiCrBUJP"
dkg_enc_key = "8sEkWbQe2Ndh79D4Q2ZZALzLXoVSkBpSuwKof8JBtwMBeZVm6ZGd21VrbDP8wAbVkKe"
sailfish_address = "172.20.0.4:8000"

[[members]]
signing_key = "qh3tJ83Ko7f6B9ksPj8PPwTshFmToj9zbjcgPCegar7m"
dh_key = "CetqwdEDC8BkBXB9wpTmuumCsj2kRPcq9hbJVEdaQ7r9"
dkg_enc_key = "8sy6StkPxaNZ7qdUQESbAdZamPC4uERddXfHXaLoyagpmjrnafnQhF4r1Gh5ThzsNhX"
sailfish_address = "172.20.0.5:8000"

[[members]]
signing_key = "i5ccK9sZFtdWpB6rp4deJKvb8UNMCYhxj7G2sGBAsdam"
dh_key = "6czLW5NW4C74eQUBdzwHGmUzA5B8vbWpuH6amZHXtPnq"
dkg_enc_key = "8t7p3VfTCMXxEAPrcLzMHiANGmEd2Y5aLkKAgrpe5ZyEmgGm2MR1ypweLbCw5RdXySe"
sailfish_address = "172.20.0.6:8000"
