id = 0
effective_timestamp = "2025-09-15T17:42:44Z"

[[members]]
signing_key = "pJotdcLwmkXAb33kZJE8xpVH61h2b7Qo49yP7jCY25mF"
dh_key = "hHbUMPNsfFrCh281dpCUPLC8ytsbVTsGmKdrrwbHAH3"
dkg_enc_key = "5m8oT54tJNB8mmesBfV8ivnufDjjTNbS7rKe7tz1Z8MVQU65KgurVMLmP37ZkE9bpR"
public_address = "node0:8000"
http_api = "node0:8004"
internal_api = "node0:8003"

[[members]]
signing_key = "2AayoEeoGV5Hd6Q6TcvtkD8brWaLforFCQgNZtBGMThqN"
dh_key = "5QABVAY5Cqp615YQjfvGQd2JAPD4xpaYK8hx69Ljopoj"
dkg_enc_key = "6VHgaqs8k53hE3NDqeDtxujye95Vk49rucE28cb7oygezHTCsWDCSSjetQ488iw9cr"
public_address = "node1:8000"
http_api = "node1:8004"
internal_api = "node1:8003"

[[members]]
signing_key = "xjgK4BPUDXpv1oTCUrFABpDxVE9tuxfrSwvjuSrSU4rU"
dh_key = "G9eSPKSU6CAb4egagEXvDJ5xyXUw6uN7SMo9XgMTS1Uh"
dkg_enc_key = "5zVtxDp8EPmtzk1KWszLD3ERQt7ChT6kymsKDxJf5q44q8YwhBnNWKDe6gwJbMYggK"
public_address = "node2:8000"
http_api = "node2:8004"
internal_api = "node2:8003"

[[members]]
signing_key = "pTTLYSuuaZk5wZ4QpkdjrmAHt2ppuXt3n5M6xxvH6Y6N"
dh_key = "JAhQ1HmLWL9ynAz1KXP1TG8WznZp9rTSGYW7nqRCn3pJ"
dkg_enc_key = "7ZHrctw1bjaumyUd4S9osyLJiujDsfjbF4jGtc2LSybMndU5Q1qeNwFu2Q1kdp7YBH"
public_address = "node3:8000"
http_api = "node3:8004"
internal_api = "node3:8003"

[[members]]
signing_key = "cBBhrxp89nuSzigBoJxwBQ7CTm45RxLedrUrbwFHayZk"
dh_key = "Ewh9z7y64Zd3tKDXpTqhb9FsFaxaANna7Vqr6zj92pF5"
dkg_enc_key = "6aBEVAdPWfMfczvvaEajFAt9N6FqEmhZfaS4z5yRRvnSKCHSvt7Kuj2RVCmAguyM1f"
public_address = "node4:8000"
http_api = "node4:8004"
internal_api = "node4:8003"
