id = 0
effective_timestamp = "2025-09-01T02:00:00Z"

[[members]]
signing_key = "hc48HUoRWoSngFzcB1j9NgzWqf1giMRK8ZwUGRbirXDf"
dh_key = "BUVYasb9FFFHTLAq3GXumRkq2dVkFmtwdJdgrQwpJnRZ"
dkg_enc_key = "6bJf6og7E5nPsYLrtqYYudoiVhGm88jom4gzp3GouXbeQpAPc8Z8C48fae4NdBDLSz"
public_address = "172.20.0.2:8000"
http_api = "172.20.0.2:8004"
internal_api = "172.20.0.2:8003"

[[members]]
signing_key = "ra3qtN6y26nFpWSe5MEbyMnvuN54hE82azu5hYg6hxce"
dh_key = "CpuxwJLuXcFLr6mdpqAp3vRZChtH6xVqxro9YcD9rH9k"
dkg_enc_key = "6H2qo1piFuhKgW22bgHxcTbzh9JAQocK77KqfsCtaNx8HaL3GYir4QG2tJkfoBKfQU"
public_address = "172.20.0.3:8000"
http_api = "172.20.0.3:8004"
internal_api = "172.20.0.3:8003"

[[members]]
signing_key = "iUpUHyk3vongZ1LuVjP3AH5cjHTSiJb9Cgtsi53CwtYM"
dh_key = "Bt3CVThACdYeSapFZvaa3PpxVHcQ5znWwpEhVENJJrFF"
dkg_enc_key = "7Jeas4FYbhY2uuzM4HWthHDXRTnsZzqCiykDetVTVjctbkAYZQno7KVvTizPwQ2q2g"
public_address = "172.20.0.4:8000"
http_api = "172.20.0.4:8004"
internal_api = "172.20.0.4:8003"

[[members]]
signing_key = "mnMw9aV8hRuZJJfXw24X9xQkMNRm29F69KQkZdFCAWRm"
dh_key = "FgJ5RWL769YBTT4eNimJp5dfAqLshrUAqdBCCZtgcrbm"
dkg_enc_key = "5yRtZSeQU4f16oHxkJbFph9bcbVQ1yoy7fx2jiXnDyBkCfZYfRKqRVRH6ps83izUcw"
public_address = "172.20.0.5:8000"
http_api = "172.20.0.5:8004"
internal_api = "172.20.0.5:8003"

[[members]]
signing_key = "ewYeKQvaC3QDjrSC9aS2bQL1CJZNYFBmWmg76TzmGtan"
dh_key = "D4MUChEMCKo1ZfgkPU12PFe9ZfbiUVqH95Gie3uqEPXC"
dkg_enc_key = "5xbbdsfegZDv2vpJ2CrhTiF1EbfsMfB9mkmsATkaxhkXQdnwu5g2AuLUba4THigwMz"
public_address = "172.20.0.6:8000"
http_api = "172.20.0.6:8004"
internal_api = "172.20.0.6:8003"
