effective_timestamp = "2025-09-01T02:00:00Z"

[[members]]
signing_key = "uf6oKVCphzAd1Y87UyK1hLfRz7pJJ8LSC393jzAbHKmZ"
dh_key = "3eP89nLTHxHaVR6kdMhorBeM77ndbe2TtgX1am76BSGW"
dkg_enc_key = "69nv9n7FNSHVeepYq3JBizQkBySZ4pq3YRdB1f574roqmiv2RBpCtDeQqi4igruC55"
public_address = "172.20.0.2:8000"
http_api = "172.20.0.2:8004"
internal_api = "172.20.0.2:8003"

[[members]]
signing_key = "z6FrBScyGgtbkbD7LzUfYWGHKnpF9XzrZw81ENPunFLW"
dh_key = "8hMVYLCeffEWAsk147ny4Z71AVHA619L1ijmMVmba7GD"
dkg_enc_key = "7ajdb8uCeehrXr1yaHF3wtgSKpxf9YEYKBwg2QsapZeRGnbD2MZcUx36rVyhU8AQwr"
public_address = "172.20.0.3:8000"
http_api = "172.20.0.3:8004"
internal_api = "172.20.0.3:8003"

[[members]]
signing_key = "h2sXHz4BuHF7hi1av6yQbsUgFKjYCNDhf5KhtTbWv2WE"
dh_key = "FHzdL3wZvaNdA9kfqBmJjAwpGckS8xWquhBdNMrzckNz"
dkg_enc_key = "7drbfCdN7vkYhZhN96KHLFDSgPBrmWXHw3o9i3HA7wjUcbGntMCHrhNo4rYLHsgg3X"
public_address = "172.20.0.4:8000"
http_api = "172.20.0.4:8004"
internal_api = "172.20.0.4:8003"

[[members]]
signing_key = "uxkURysS7THRSkKUDW22R5LWAEkKVepjLDpHRa5jB6MK"
dh_key = "4HZj5ysKMsPobkAMnJytnQvf3NsVSLSkY3N9nBzDfCrc"
dkg_enc_key = "7n6vbt3zsTUifwkGngct9QMc9JqwT3ALvY2uYaKfkk5FDFKZgTSdnoboKr68BiveYv"
public_address = "172.20.0.5:8000"
http_api = "172.20.0.5:8004"
internal_api = "172.20.0.5:8003"

[[members]]
signing_key = "2BH8XmMRMRM2od6gVB9BUnKaoVPbHoZBFaA7F3Qvu5ciS"
dh_key = "4w1eDWLNaiST6LxLGivqhdPwJGrfJf7DXo7SFVdhSmFY"
dkg_enc_key = "72bMFtCgLjrDDCMoFKSSgqBLoMW7dzStRQXaNG6hW3w9TkWM3GtmpJdDGo6YRPf2Hn"
public_address = "172.20.0.6:8000"
http_api = "172.20.0.6:8004"
internal_api = "172.20.0.6:8003"
