effective_timestamp = "2025-09-01T02:00:00Z"

[[members]]
signing_key = "2BnRw2jfCamT71MkxYpgAJKJQhpLWcMXnCigS75hU1qih"
dh_key = "BxXmTXxJfA6ZKdMDDen4c3bgXvCj31uRKWnRonG3Yv7K"
dkg_enc_key = "5uLpmZgdePFeojPzWZMGFbGRdWEhvf1f4eqWnqSigaMNH7uCqN1gCHLfujCqT7KgmV"
public_address = "172.20.0.2:8000"

[[members]]
signing_key = "29C58aPGH7bmkZSXDqnChTfyGVFBm5NeosWZDRBA9Ux3d"
dh_key = "2GipuWineN4eVpiyv77ztF7xzymJNettLX2WBjnKRk48"
dkg_enc_key = "5iNu4kPU7rU4kJ5P8qzm5dKGexD1C2zkQEdHCw79iYQTpeavcFNsXU3dKt8hqHZiqA"
public_address = "172.20.0.3:8000"

[[members]]
signing_key = "2BRkGavaUHy7ZDrr3F6vdoACq4qRUnE79PWP2umEkJgay"
dh_key = "ERtb9N6bEfYyzxUtaZzGVazP4RCFnLGfWL6S2FK1Jv4c"
dkg_enc_key = "6Z4uKNhZSMMiscDWEynVKrKmvsFJoGsAJcRgiBmftAhT2Ps3KE5EHS3xRN1K3yAegw"
public_address = "172.20.0.4:8000"

[[members]]
signing_key = "uXxASBe2Lu5kMfKK1ktAN1upw3rVLPJ51tZqM5ZgcA7D"
dh_key = "Gni5HjhtQuqAgwHAEgU4ETxX2q2ir8ThPjpmjnkL8cff"
dkg_enc_key = "77yBMksjiH6Dtzv897UQt1w1N2z4r1w37HGu9KqeaG1Wz8khXvenMKCgA8B8Y1ojS7"
public_address = "172.20.0.5:8000"

[[members]]
signing_key = "24KKPys4WkVwvS7FgCi5FWHpfsWNQWLoxmfzr3z14FjD9"
dh_key = "BDbKk2ZQEfdib8nrEnbcajJBboCL93GqiN5xfWxBcno8"
dkg_enc_key = "5nmDcipjEYt5eHxPBRHyZqGLLSXm32ZQSFf5iCtQz3FqzeiJUjksrm5HVEmSp3nqKD"
public_address = "172.20.0.6:8000"
