[net.public]
address = "172.20.0.3:8000"

[net.internal]
address = "172.20.0.3:8003"

[keys.signing]
secret = "8kwLZ4oxk4nziKVcBdEgtLw6EWbr1upZok25eokkQDQV"
public = "29C58aPGH7bmkZSXDqnChTfyGVFBm5NeosWZDRBA9Ux3d"

[keys.dh]
secret = "DdmvCssArjzyZGzkA2vBtAJhQ9KRJyG9cWWnFWRMik1B"
public = "2GipuWineN4eVpiyv77ztF7xzymJNettLX2WBjnKRk48"

[keys.dkg]
secret = "7jRTtZ6U1opcHV3Nypt9Dn6jB2JXYeu62FwuHGW6LLy"
public = "5iNu4kPU7rU4kJ5P8qzm5dKGexD1C2zkQEdHCw79iYQTpeavcFNsXU3dKt8hqHZiqA"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
