committee = 0
stamp = "/tmp/timeboost.0.stamp"

[net.public]
address = "node0:8000"
http-api = "node0:8004"

[net.internal]
address = "node0:8003"
nitro = "nitro0:55000"

[keys.signing]
secret = "HT9GaCeE2DQvxoWGjQSehTMHeie8jkMPT7jyCQBeKaBR"
public = "pJotdcLwmkXAb33kZJE8xpVH61h2b7Qo49yP7jCY25mF"

[keys.dh]
secret = "35uUtcJikRRH1TuVQn2LQu1Giv4ShjBVGemniKX9qvob"
public = "hHbUMPNsfFrCh281dpCUPLC8ytsbVTsGmKdrrwbHAH3"

[keys.dkg]
secret = "4NdGg1zBF9Uwr6fjg2kEZspQqscAYe4qBHUMf81vbALX"
public = "5m8oT54tJNB8mmesBfV8ivnufDjjTNbS7rKe7tz1Z8MVQU65KgurVMLmP37ZkE9bpR"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
ws-url = "ws://demo-l1-network:8546/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
