[net.public]
address = "172.20.0.3:8000"

[net.internal]
address = "172.20.0.3:8003"

[keys.signing]
secret = "FWJzNGvEjFS3h1N1sSMkcvvroWwjT5LQuGkGHu9JMAYs"
public = "vGKKAxVNfkSCdn8qh36nXdSZqyhPq644sQBoeZtcEUCR"

[keys.dh]
secret = "4hjtciEvuoFVT55nAzvdP9E76r18QwntWwFoeginCGnP"
public = "FHTJAk6oyt3jefEp1ZrPEn2MkqRt2LibEFd57AnEUZdb"

[keys.dkg]
secret = "ARtqWGmRWrBqZUr4MmiLaPgzjsiKp5USsC9iQNRMZYy4"
public = "7p1BtEz7WnFMt6Hr28X3Rngqza6i8hRoswhzZRFd6GzgkspLKHBfDocHP8DwzXiNiZ"

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
