[net]
public = "172.20.0.4:8000"
internal = "172.20.0.4:11000"

[keys.signing]
secret = "Fg3tVVbB4UX5cTcqicFkk1ApbUJ71zq9m86ffiBHerTn"
public = "21R4uDwS7fdxsNPWy92DArC575sYiQdEasFBVEpH8m53e"

[keys.dh]
secret = "221uwQa7dhYyzwwVQcBF4TAkmyjEcZ5egbrtUN5P3uKq"
public = "DRYKr9pHPf6i6QmQiAihrQnEqEYXg96fe5kyMiCrBUJP"

[keys.dkg]
secret = "AZzpp7m2d2b2pWgmAVWt6zqgg7pd95tngBsA9LFj4CjrC"
public = "8sEkWbQe2Ndh79D4Q2ZZALzLXoVSkBpSuwKof8JBtwMBeZVm6ZGd21VrbDP8wAbVkKe"

[chain_config]
parent_chain_id = 31337
parent_chain_rpc_url = "http://127.0.0.1:8545/"
parent_ibox_contr_addr = "0x4dbd4fc535ac27206064b68ffcf827b0a60bab3f"
parent_block_tag = "finalized"
key_manager_contr_addr = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
