[net.public]
address = "172.20.0.2:8000"

[net.internal]
address = "172.20.0.2:8003"

[keys.signing]
secret = "335kcysDXn8fcVH15atKudPVyw293pKfFTEyAQdzMnVT"
public = "29tCfY85eWVArDFEFCGeXK3dT58BpJx5J4uan2drWEks5"

[keys.dh]
secret = "6dgEs1pjE1LX9YrsrgtiuuwDd8yL5KXKwH4SgHkXT6Re"
public = "cd7c1tMyuFHP8Fez32gXM3GKB4jvtECpq2s218kTVNh"

[keys.dkg]
secret = "Bzd3qGB2RYVWMKN8j3P4HAtNfSy1ndizqQZ925sxxC4b"
public = "6ECoTbFcsPdx6EYuqggdNUxUtncdg8p622DLxGqMAG3JTDUg7GBduxgFtemwgTFtmS"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
