stamp = "/tmp/timeboost.3.stamp"

[net.public]
address = "172.20.0.5:8000"
http-api = "172.20.0.5:8004"

[net.internal]
address = "172.20.0.5:8003"

[keys.signing]
secret = "C3S84dgsyHhrc5nEhCgBRe8zBaEHbEcwWz5fbShCZvU1"
public = "uxkURysS7THRSkKUDW22R5LWAEkKVepjLDpHRa5jB6MK"

[keys.dh]
secret = "BCnTCKitRJewSgZo8jVn7SU1PpPhRenBkUXy7AhuBwku"
public = "4HZj5ysKMsPobkAMnJytnQvf3NsVSLSkY3N9nBzDfCrc"

[keys.dkg]
secret = "8vkvBsFk2uZ4ci7UGvhNKAT8eXBkBSd9xMxgrDa2Szgx"
public = "7n6vbt3zsTUifwkGngct9QMc9JqwT3ALvY2uYaKfkk5FDFKZgTSdnoboKr68BiveYv"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
ws-url = "ws://127.0.0.1:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
