[net]
sailfish_address = "172.20.0.5:8000"
decrypt_address = "172.20.0.5:9000"
certifier_address = "172.20.0.5:10000"
internal_address = "172.20.0.5:11000"

[keys]
signing_key = "qh3tJ83Ko7f6B9ksPj8PPwTshFmToj9zbjcgPCegar7m"
dh_key = "CetqwdEDC8BkBXB9wpTmuumCsj2kRPcq9hbJVEdaQ7r9"
dkg_enc_key = "8sy6StkPxaNZ7qdUQESbAdZamPC4uERddXfHXaLoyagpmjrnafnQhF4r1Gh5ThzsNhX"

[chain_config]
parent_chain_id = 31337
parent_chain_rpc_url = "http://127.0.0.1:8545/"
parent_ibox_contr_addr = "0x4dbd4fc535ac27206064b68ffcf827b0a60bab3f"
parent_block_tag = "finalized"
key_manager_contr_addr = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[private]
signing_key = "FvNPFm2VySb2hasVFSgRyzSjnDy73BDL7XJfRmGy4SST"
dh_key = "3SxqfGusCVtc6oujqVPtkwKdhbN1aUKMNQbbhZZoExNu"
dkg_dec_key = "AebFdmKfLJTCqHtErnRySZCLsLv9gH7x4DXTAWNWrqj1P"
