committee = 0
stamp = "/tmp/timeboost.1.stamp"

[net.public]
address = "node1:8000"
http-api = "node1:8004"

[net.internal]
address = "node1:8003"
nitro = "nitro1:55000"

[keys.signing]
secret = "8HbuE746bZfeUHSbot6nm7GAryN7XRjKmbWBwicGSRbc"
public = "2AayoEeoGV5Hd6Q6TcvtkD8brWaLforFCQgNZtBGMThqN"

[keys.dh]
secret = "F8uutS7PLwNyrr3QggkWyRxdUPHxpRVW7oZmbdBVcMpY"
public = "5QABVAY5Cqp615YQjfvGQd2JAPD4xpaYK8hx69Ljopoj"

[keys.dkg]
secret = "H6i7wU348D5RN8vTaaauopSDQdBydVAHmjrw23TRTtVV"
public = "6VHgaqs8k53hE3NDqeDtxujye95Vk49rucE28cb7oygezHTCsWDCSSjetQ488iw9cr"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
ws-url = "ws://demo-l1-network:8546/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
