committee = 0
stamp = "/tmp/timeboost.2.stamp"

[net.public]
address = "node2:8000"
http-api = "node2:8004"

[net.internal]
address = "node2:8003"
nitro = "nitro2:55000"

[keys.signing]
secret = "2n6GZjsizPooAHzMeRnYFubayS6A9Pv5tXpPkhwT4ZRG"
public = "xjgK4BPUDXpv1oTCUrFABpDxVE9tuxfrSwvjuSrSU4rU"

[keys.dh]
secret = "3cQBUTqRCDkJQ9SXeAejX6xqrag3hyYw47n63vuzpiPS"
public = "G9eSPKSU6CAb4egagEXvDJ5xyXUw6uN7SMo9XgMTS1Uh"

[keys.dkg]
secret = "5Q9hzpSBHzShP5vHH2uiVS6CPzTcNyciVRGRLqZwn3qc"
public = "5zVtxDp8EPmtzk1KWszLD3ERQt7ChT6kymsKDxJf5q44q8YwhBnNWKDe6gwJbMYggK"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
ws-url = "ws://demo-l1-network:8546/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
