[net.public]
address = "172.20.0.3:8000"

[net.internal]
address = "172.20.0.3:8003"

[keys.signing]
secret = "5eWwi4LWRWpzH8HDEeyRadcTNNCtJcj7gVunQW7VST4z"
public = "dNpCHvXpQipWwUX4iunYfPJqyJuY9McjTHAMi8hvnPmj"

[keys.dh]
secret = "4iTPZTMBgx1QkkTo3oQHkhWZ6XJmgHBqqnMSAwf9rPMv"
public = "3f2trYsMhD1LRQAkraKXgRDyoCXPbAQERhyX3xbkAffp"

[keys.dkg]
secret = "GZbWRWTLHDBhW1g2BixyCrjb1pt4k2BGSd4RbUjFoZDN"
public = "6w3gynsk5rMarufwa7LHM1tosnYE3GrYRKR2mdFs6RyBSt1pfQvdeKUn79rzMqdt5j"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
