stamp = "/tmp/timeboost.3.stamp"

[net.public]
address = "172.20.0.5:8000"
http_api = "172.20.0.5:8004"

[net.internal]
address = "172.20.0.5:8003"

[keys.signing]
secret = "CUpkbkn8bix7ZrbztPKJwu66MRpJrc1Wr2JfdrhetASk"
public = "v6UBdLT5BvMhLW7iKv7M2xYeaW2SCAsnZ5PiSg6AaKfA"

[keys.dh]
secret = "5KpixkV7czZTDVh7nV7VL1vGk4uf4kjKidDWq34CJx1T"
public = "Do2GmAexW5MUdD8nToDiBWGbDgk1AwXoxtLTyirDtKQh"

[keys.dkg]
secret = "7vWcVJDAhfSvmtm1L7KZvoD9agx6hyy9FvA75xWpjxK7"
public = "7aZBFZUEbXxFH9SiGJeUyjzas4mYJ1R13mTPsPeawVU7JFuocfvX9XsRT8qgr17RCe"

[chain]
namespace = 10101

[chain.parent]
id = 412346
rpc_url = "http://172.20.0.12:8547/"
ws_url = "ws://172.20.0.12:8547/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base_url = "https://query.decaf.testnet.espresso.network/v1/"
websockets_base_url = "wss://query.decaf.testnet.espresso.network/v1/"
