stamp = "/tmp/timeboost.4.stamp"

[net.public]
address = "172.20.0.6:8000"
http_api = "172.20.0.6:8004"

[net.internal]
address = "172.20.0.6:8003"

[keys.signing]
secret = "6LMMEuoPRCkpDsnxnANCRCBC6JagdCHs2pjNicdmQpQE"
public = "tV66KknkDH47hRSNzwJtt7Q7EZtxVxQsNnUGoAJdDn6J"

[keys.dh]
secret = "39wAn3bQzpn19oa8CiaNUFd8GekQAJMMuzrbp8Jt3FKz"
public = "HXaesvEGFiDgrVTix1fKzSLTarFexTZSJD6ymSrF7vPL"

[keys.dkg]
secret = "GFvv2wcQmiGpk5rFp1FGpeUjnVUyZmGM9k8VHb1Jn7EG"
public = "6R69TzDg3jo1MTex9Uter9XQud458YPpSvXirkYdS295PV81CRvgz5jVWQbkCpZnYV"

[chain]
namespace = 10101

[chain.parent]
id = 412346
rpc_url = "http://172.20.0.12:8547/"
ws_url = "ws://172.20.0.12:8547/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base_url = "https://query.decaf.testnet.espresso.network/v1/"
websockets_base_url = "wss://query.decaf.testnet.espresso.network/v1/"
