stamp = "/tmp/timeboost.2.stamp"

[net.public]
address = "172.20.0.4:8000"
http-api = "172.20.0.4:8004"

[net.internal]
address = "172.20.0.4:8003"

[keys.signing]
secret = "A93KRMuKoFMGnW7XcPqqgqCprTX4iczCad6mpQXe9L2X"
public = "iUpUHyk3vongZ1LuVjP3AH5cjHTSiJb9Cgtsi53CwtYM"

[keys.dh]
secret = "Fn891W26UJphbmMNz757q3zHd7Hf73b79rri5tBNAmqN"
public = "Bt3CVThACdYeSapFZvaa3PpxVHcQ5znWwpEhVENJJrFF"

[keys.dkg]
secret = "3e1DHq9Zhob58y8ApF9EpSHeB3hvgxEWUY3K6re3HM5y"
public = "7Jeas4FYbhY2uuzM4HWthHDXRTnsZzqCiykDetVTVjctbkAYZQno7KVvTizPwQ2q2g"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://172.20.0.11:8545/"
ws-url = "ws://172.20.0.11:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
