[net.public]
address = "172.20.0.5:8000"

[net.internal]
address = "172.20.0.5:8003"

[keys.signing]
secret = "GV8KqDGPN6L5TTUi2NGnbR913kNUfrKBj1xAnr9RzMzp"
public = "uXxASBe2Lu5kMfKK1ktAN1upw3rVLPJ51tZqM5ZgcA7D"

[keys.dh]
secret = "HVLXS4H8jtMLb6GwmhKxan251z11c3KcLUm2NpAbFmR8"
public = "Gni5HjhtQuqAgwHAEgU4ETxX2q2ir8ThPjpmjnkL8cff"

[keys.dkg]
secret = "43tDarZnbsYZHHb7M1ec6dN8KkbqLcbYghDyeHQzmim7"
public = "77yBMksjiH6Dtzv897UQt1w1N2z4r1w37HGu9KqeaG1Wz8khXvenMKCgA8B8Y1ojS7"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
