[net.public]
address = "172.20.0.5:8000"

[net.internal]
address = "172.20.0.5:8003"

[keys.signing]
secret = "C7nhKPtwvP4rCuYUi43NHNgUf9dBMgYjrZ5NGsiog5Cw"
public = "s2N7a6uqsSWTpgnnqwgEDUGsPJgNDPgbz9d7xu52QxxT"

[keys.dh]
secret = "99SdryHcQ6nrnUcieg5gwuPnDeH8syKQybxEj27M4RzM"
public = "uSqBJpmhzeDa3C9n64TxBWsvmC59UjaeEdJNRofZMzL"

[keys.dkg]
secret = "HnAzTpM3xbLbNwzxpfUQiYS9TCWpW6rn7DSaJA9f2Kf8"
public = "6swNFdheREU3Rncrir7ExkpUUggtsn2nEGYX9TpK7xh3JgBjwDChGmRRM4BRvW8VUF"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
