committee = 0
stamp = "/tmp/timeboost.2.stamp"

[net.public]
address = "172.20.0.4:8000"
http-api = "172.20.0.4:8004"

[net.internal]
address = "172.20.0.4:8003"
nitro = "172.20.0.12:55000"

[keys.signing]
secret = "2yWTaC6MWvNva97t81cd9QX5qph68NnB1wRVwAChtuGr"
public = "264jMLf85hfufg4ck97Hw2jiL6i1PHNoGUqxUqfhtssaE"

[keys.dh]
secret = "Fo2nYV4gE9VfoVW9bSySAJ1ZuKT461x6ovZnr3EecCZg"
public = "63eYNKoW2PsWZFhHHj3eZwHTdPE7gEjEDM7gGeDf9Uaj"

[keys.dkg]
secret = "77r7T3En7NNQvRA81G5hLhJD3VpnigJdkPonX3oAwWkX"
public = "62bnAAbU58zZUcGqy9JKGZRZHkm3g7JZB2DtJGQyChXQBPGvXSS6fF21yoxiVuD1eb"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://172.20.0.11:8545/"
ws-url = "ws://172.20.0.11:8546/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "http://172.20.0.14:41000/v1/"
websockets-base-url = "ws://172.20.0.14:41000/v1/"
max-transaction-size = 1048576
