stamp = "/tmp/timeboost.0.stamp"

[net.public]
address = "172.20.0.2:8000"
http-api = "172.20.0.2:8004"

[net.internal]
address = "172.20.0.2:8003"

[keys.signing]
secret = "Efs9gd7guWeufo4RHFGk65JVDLDPAc8hD5GRu6Xsm2aT"
public = "hc48HUoRWoSngFzcB1j9NgzWqf1giMRK8ZwUGRbirXDf"

[keys.dh]
secret = "7FiYDQLbqWi1rZPGDFPKyAT66BnoARCyim994jj5EGTs"
public = "BUVYasb9FFFHTLAq3GXumRkq2dVkFmtwdJdgrQwpJnRZ"

[keys.dkg]
secret = "3cyu7RPqu71f491UVs7RpB4ovdQJkvzg2Bg4f1DCa8kM"
public = "6bJf6og7E5nPsYLrtqYYudoiVhGm88jom4gzp3GouXbeQpAPc8Z8C48fae4NdBDLSz"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://172.20.0.11:8545/"
ws-url = "ws://172.20.0.11:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
