[net.public]
address = "172.20.0.2:8000"

[net.internal]
address = "172.20.0.2:8003"

[keys.signing]
secret = "3F6bZm4hgCeZvDSG1esihU8o6GYnyJCw7w2YxHYgJQsi"
public = "2BnRw2jfCamT71MkxYpgAJKJQhpLWcMXnCigS75hU1qih"

[keys.dh]
secret = "H18QZVbPLdG4tutdU2jcXNsAPaaZnYuc6vy38o33YGjs"
public = "BxXmTXxJfA6ZKdMDDen4c3bgXvCj31uRKWnRonG3Yv7K"

[keys.dkg]
secret = "DVnoRjcVmrM4fKBjkrjL6oxmyBpjXexHujaqacrGtQPj"
public = "5uLpmZgdePFeojPzWZMGFbGRdWEhvf1f4eqWnqSigaMNH7uCqN1gCHLfujCqT7KgmV"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
