committee = 0
stamp = "/tmp/timeboost.4.stamp"

[net.public]
address = "node4:8000"
http-api = "node4:8004"

[net.internal]
address = "node4:8003"
nitro = "nitro4:55000"

[keys.signing]
secret = "25F14EV7phpiQzdapixzeBvcuxP4a2C7CD6HbrsLeZSG"
public = "cBBhrxp89nuSzigBoJxwBQ7CTm45RxLedrUrbwFHayZk"

[keys.dh]
secret = "5MBEoyG3zDjmdBjJLwaGR9XskVasZgHbiXKEJ6wjGcer"
public = "Ewh9z7y64Zd3tKDXpTqhb9FsFaxaANna7Vqr6zj92pF5"

[keys.dkg]
secret = "9wayW8Nb5Bj6ccrcvQofiDWGYK69QYpaWrFtAAXxdFau"
public = "6aBEVAdPWfMfczvvaEajFAt9N6FqEmhZfaS4z5yRRvnSKCHSvt7Kuj2RVCmAguyM1f"

[chain]
namespace = 412346

[chain.parent]
id = 1337
rpc-url = "http://demo-l1-network:8545/"
ws-url = "ws://demo-l1-network:8546/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "http://espresso-dev-node:41000/v1/"
websockets-base-url = "ws://espresso-dev-node:41000/v1/"
max-transaction-size = 1048576
