stamp = "/tmp/timeboost.2.stamp"

[net.public]
address = "172.20.0.4:8000"
http-api = "172.20.0.4:8004"

[net.internal]
address = "172.20.0.4:8003"

[keys.signing]
secret = "GU5LjuT9URRVx7cQWWjDkNhLsJxkjanYX8hcHD2pEYdL"
public = "h2sXHz4BuHF7hi1av6yQbsUgFKjYCNDhf5KhtTbWv2WE"

[keys.dh]
secret = "86VFr8qEcTuxuzXuVgugwUTA8WNExUKut6KSsMgY9DBZ"
public = "FHzdL3wZvaNdA9kfqBmJjAwpGckS8xWquhBdNMrzckNz"

[keys.dkg]
secret = "8F5bTw1yVe8u49VmJpxAapVtcmKXQsPpVAvRjRePo8Rx"
public = "7drbfCdN7vkYhZhN96KHLFDSgPBrmWXHw3o9i3HA7wjUcbGntMCHrhNo4rYLHsgg3X"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
ws-url = "ws://127.0.0.1:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
