[net.public]
address = "172.20.0.4:8000"

[net.internal]
address = "172.20.0.4:8003"

[keys.signing]
secret = "CHuGGdBVWpcLe3Xqu3cSJHAXJkWJTmzvNWuBTGfTX43S"
public = "s7U7rTd3WQg9i3BbA9PFch1X5Lg4cDuKwsoRjtRYDe4h"

[keys.dh]
secret = "7vK7r3aNr59DBgPpSkDybgyqv6Wm5N5Uidn3jbkzNAHS"
public = "G1vvMzjqZtQ1t4QYSpsa9quytcQiK6C7SABW8dksYDAv"

[keys.dkg]
secret = "C84xNDdgiA5xfRxc77St1p1jgjtM1gqVa57ChKt4Vv9w"
public = "68UqSzoZriK2LrkR5awEXf7p25zK6mhQiCfXuf2HQss9ADM6XcbxsAFdWdBZNFzpxp"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
