[net.public]
address = "172.20.0.4:8000"

[net.internal]
address = "172.20.0.4:8003"

[keys.signing]
secret = "3caaCJTy8vvjFTDSchLW3jrc7CZ5ba76hb66tAAZxziY"
public = "2BRkGavaUHy7ZDrr3F6vdoACq4qRUnE79PWP2umEkJgay"

[keys.dh]
secret = "9KAe4uhESJMPGR21FjNm3ym2XyZ5stE4LeVi6uUFjENL"
public = "ERtb9N6bEfYyzxUtaZzGVazP4RCFnLGfWL6S2FK1Jv4c"

[keys.dkg]
secret = "9nSoAsPoVyMMLXaguJsQT5skWrv2yBhAZc5CPzf5x3cE"
public = "6Z4uKNhZSMMiscDWEynVKrKmvsFJoGsAJcRgiBmftAhT2Ps3KE5EHS3xRN1K3yAegw"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
