[net.public]
address = "172.20.0.6:8000"

[net.internal]
address = "172.20.0.6:8003"

[keys.signing]
secret = "CqTxmb6fUUFGY3U93BmNhUZaeq29fitnNgHdMzjFryjH"
public = "25pFV1wkQxgHzkG7exVLGfMN3t5gKVHUJqoNFktMfGmH7"

[keys.dh]
secret = "3pbxhe9q98YqUgf6Vd28GvxkyEvAfAp2mt9gBov7rtvz"
public = "66WjxaBwEsyzMivKULHfrehZTsgG5knMXyVPjbEATaa7"

[keys.dkg]
secret = "DsVdMpRn1PxveQA3ZA3ZmSnm99bV2ZrT8H25JLFpcqYQ"
public = "79NZ6hfVSqLBsQN3gUwb5WSHXwYWJtuv3Xybnw3Wc2ry7ejaqZE6q2isHCBAmfWKfo"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
