[net.public]
address = "172.20.0.6:8000"

[net.internal]
address = "172.20.0.6:8003"

[keys.signing]
secret = "C2V4duPu64AQfqFLhRpYxSsnGvwdDAsratqmbGhrtEhM"
public = "24KKPys4WkVwvS7FgCi5FWHpfsWNQWLoxmfzr3z14FjD9"

[keys.dh]
secret = "6iKyMErKjJdHHWuNhSnGxG7jh1L6Zx8MeHATv7vW9YLb"
public = "BDbKk2ZQEfdib8nrEnbcajJBboCL93GqiN5xfWxBcno8"

[keys.dkg]
secret = "Aaxf2zWrv7HmBmkC1TBMQX8GCaLw8yPbZhKo2Q9hSPa7"
public = "5nmDcipjEYt5eHxPBRHyZqGLLSXm32ZQSFf5iCtQz3FqzeiJUjksrm5HVEmSp3nqKD"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc_url = "http://127.0.0.1:8545/"
ibox_contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block_tag = "finalized"
key_manager_contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"
