[package]
name = "timeboost-crypto"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
sha2 = { version = "0.10", default-features = true }
aes-gcm = { version = "0.10.3" }
ark-std = { workspace = true }
ark-poly = { workspace = true }
ark-ff = { workspace = true }
zeroize = { version = "1.5", default-features = false }
anyhow = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
