[package]
name = "timeboost-crypto"
version.workspace = true
edition.workspace = true
description.workspace = true

[features]
test = []

[dependencies]
ark-bn254 = { workspace = true }
ark-ed-on-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-std = { workspace = true }
ark-ff = { workspace = true }
zeroize = { version = "1.5", default-features = false }
anyhow = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
