[package]
name = "timeboost-crypto"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
aes-gcm = { workspace = true }
anyhow = { workspace = true }
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
ark-serialize = { version = "0.4.2", features = ["derive"] }
ark-std = { workspace = true }
bitvec = { workspace = true }
blake3 = { workspace = true }
digest = { workspace = true }
displaydoc = { workspace = true }
jf-signature = { workspace = true }
jf-utils = { workspace = true }
multisig = { path = "../multisig", features = ["tagged-base64"] }
nimue = { workspace = true }
primitive-types = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
tagged-base64 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
typenum = { workspace = true }
vbs = { workspace = true }
