{
 "title": "Local Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Timeboost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Connections (Consensus, Decrypt, Block)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sailfish_connections", "legendFormat": "__auto" },
    { "expr": "decrypt_connections", "legendFormat": "__auto" },
    { "expr": "block_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Committee",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "committee_id", "legendFormat": "__auto" }
   ]
  },
  { "title": "Sequencer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queued (Priority/Regular) Bundles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "queued_prio_bundles", "legendFormat": "__auto" },
    { "expr": "queued_reg_bundles", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queued (Encrypted/Decrypted) Bundles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "queued_encrypted_ilist", "legendFormat": "__auto" },
    { "expr": "output_decrypted_ilist", "legendFormat": "__auto" }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Committed Round",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "committed_round", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Round Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(round_duration_sum[$__rate_interval]) / rate(round_duration_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivery duration (sec)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(le) (delivery_duration_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vertex Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "vertex_buffer", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Block Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Blocks submitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "blocks_submitted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blocks verified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    { "expr": "blocks_verified", "legendFormat": "__auto" }
   ]
  }
 ]
}