[package]
name = "timeboost-networking"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
bimap = { workspace = true }
multisig = { path = "../multisig" }
parking_lot = { workspace = true }
rand = { workspace = true }
snow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
