[package]
name = "timeboost-networking"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
async-lock = { workspace = true }
bimap = "0.6"
bincode = { workspace = true }
blake3 = { workspace = true }
custom_debug = "0.5"
delegate = "0.13"
derive_builder = "0.20"
futures = { workspace = true }
lazy_static = "1"
libp2p = { package = "libp2p", version = "0.53", default-features = false, features = [
    "macros",
    "autonat",
    "cbor",
    "dns",
    "gossipsub",
    "identify",
    "kad",
    "quic",
    "request-response",
    "secp256k1",
    "serde",
    "tokio",
] }
libp2p-identity = { workspace = true }
libp2p-swarm-derive = "0.34"
pin-project = "1"
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
timeboost-util = { path = "../timeboost-util" }
timeboost-crypto = { path = "../timeboost-crypto" }
tokio = { workspace = true }
tracing = { workspace = true }
