[package]
name = "timeboost-builder"
description = "Timeboost block builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
arrayvec = { workspace = true }
bincode = { workspace = true }
bon = { workspace = true }
bytes = { workspace = true }
cliquenet = { path = "../cliquenet" }
committable = { workspace = true }
metrics = { path = "../metrics" }
multisig = { path = "../multisig" }
serde = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
timeboost-proto = { path = "../timeboost-proto" }
timeboost-types = { path = "../timeboost-types" }
tokio = { workspace = true }
tracing = { workspace = true }
