// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(uint32, tag = "1")]
    pub namespace: u32,
    #[prost(uint64, tag = "2")]
    pub round: u64,
    #[prost(bytes = "bytes", tag = "3")]
    pub payload: ::prost::bytes::Bytes,
    #[prost(bytes = "vec", tag = "4")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
