// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoAddress {
    #[prost(string, tag = "1")]
    pub hex: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub raw: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoTransaction {
    #[prost(bytes = "vec", tag = "1")]
    pub encoded_txn: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub address: ::core::option::Option<ProtoAddress>,
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoInclusionList {
    #[prost(message, repeated, tag = "1")]
    pub encoded_txns: ::prost::alloc::vec::Vec<ProtoTransaction>,
    #[prost(uint64, tag = "2")]
    pub round: u64,
    #[prost(uint64, tag = "3")]
    pub consensus_timestamp: u64,
}
