[profile.default]
slow-timeout = { period = "60s", terminate-after = 2 }

[[profile.default.overrides]]
filter = 'test(/^tests::timeboost::timeboost_handover::/)'
threads-required = 2
slow-timeout = { period = "300s", terminate-after = 1 }
