#!/bin/bash

set -euo pipefail

./get_task_ips.sh timeboost timeboost | sed 's|$|:9000/status/metrics|' | while read -r url; do echo "$url:" && curl -s -L "$url" | grep '^round ' | awk '{print $2}'; done
