#!/usr/bin/env bash

set -euo pipefail

MANAGER_MNEMONIC="attend year erase basket blind adapt stove broccoli isolate unveil acquire category"
MANAGER_ACCOUNT_INDEX=0
MANAGER_ADDRESS="0x36561082951eed7ffD59cFD82D70570C57072d02"
FAUCET_PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
URL="http://172.20.0.11:8545"
DEPLOYMENT_FILE=$(mktemp -t timeboost-deployment-XXXXX)

# Fund manager account && create deployment file
cast send --rpc-url "$URL" --value 1ether --private-key "$FAUCET_PRIVATE_KEY" "$MANAGER_ADDRESS"
RUST_LOG=info /app/deploy \
    -m "$MANAGER_MNEMONIC" \
    -i "$MANAGER_ACCOUNT_INDEX" \
    -u "$URL" \
    -o "$DEPLOYMENT_FILE"

# Extract the deployed KeyManager address
km_addr=$(sed -nr 's/^key_manager.*=.*"(.+)"/\1/p' "$DEPLOYMENT_FILE")

# Update the contract
RUST_LOG=info /app/register \
    -m "$MANAGER_MNEMONIC" \
    -i "$MANAGER_ACCOUNT_INDEX" \
    -u "$URL" \
    -k "$km_addr" \
    -c "committee.toml"

# Clean up the temporary deployment file
rm -f "$DEPLOYMENT_FILE"
