#!/bin/bash

set -euox pipefail

just build_release

i=$1

echo "Starting node $i"

RUST_LOG=timeboost=info,sailfish=info,timeboost_networking=warn \
./target/release/timeboost \
    --id $i \
    --port $((8000 + i)) \
    --rpc-port $((8800 + i)) \
    --metrics-port $((9000 + i)) \
    --base local
