#!/bin/bash

set -euox pipefail

if ! command -v uv &> /dev/null; then
  echo "Error: uv command not found. Install it with 'curl -LsSf https://astral.sh/uv/install.sh | sh'" >&2
  exit 1
fi

if [ "${1:-debug}" = "release" ]; then
    just build_release
else
    just build
fi

sudo ./scripts/run-dev-node.sh || true
timeout 5 bash -c 'until curl -sSf http://localhost:8547 -o /dev/null; do sleep 1; done'

uv run fake-contract/main.py --timeout 30 &

for i in {0..4}; do
    echo "Starting node $i"

    RUST_LOG=timeboost=debug,sailfish=debug,timeboost_networking=info \
    ./target/${1:-debug}/timeboost \
        --id $i \
        --port $((8000 + i)) \
        --rpc-port $((8800 + i)) \
        --nitro-node-url http://localhost:8547 \
        --metrics-port $((9000 + i)) &
done

wait
sudo pkill -9 nitro

