#!/bin/bash

set -euo pipefail

just build_release

nodes=${1:-5}

for (( i=0; i<$nodes; i++ )); do
    echo "Starting node $i"

    cmd=(target/release/sailfish
        --id $i
        --port $((8000 + $i))
        --keyset-file test-configs/local.json
        --tps 100
        --nodes $nodes
    )

    eval "${cmd[@]}" &
done

wait
