#!/bin/bash

set -euox pipefail
set -a; source .env; set +a;


if [ "${1:-debug}" = "release" ]; then
    just build_release
else
    just build
fi

docker run --rm --name nitro-dev -p 8547:8547 "offchainlabs/nitro-node:v3.2.1-d81324d" --dev --http.addr 0.0.0.0 --http.api=net,web3,eth,debug &
timeout 30 bash -c 'until curl -sSf http://localhost:8547 -o /dev/null; do sleep 1; done' || exit 1

for i in {0..4}; do
    echo "Starting node $i"

    SIGNATURE_PRIVATE_KEY="TIMEBOOST_DEMO_SIGNATURE_PRIVATE_KEY_$i"
    DECRYPTION_PRIVATE_KEY="TIMEBOOST_DEMO_DECRYPTION_PRIVATE_KEY_$i"

    RUST_LOG=timeboost=debug,sailfish=debug,cliquenet=info \
    TIMEBOOST_SIGNATURE_PRIVATE_KEY=${!SIGNATURE_PRIVATE_KEY} \
    TIMEBOOST_DECRYPTION_PRIVATE_KEY=${!DECRYPTION_PRIVATE_KEY} \
    ./target/${1:-debug}/timeboost \
        --id $i \
        --http-port $((8800 + i)) \
        --nitro-node-url http://localhost:8547 \
        --keyset-file test-configs/local.json &
done

wait
pkill -f nitro
