#!/bin/bash

set -euox pipefail

just build_release --features until

for i in {0..4}; do
    echo "Starting node $i"

    RUST_LOG=timeboost=info,sailfish=info,timeboost_networking=warn \
    ./target/release/timeboost \
        --id $i \
        --port $((8000 + i)) \
        --rpc-port $((8800 + i)) \
        --metrics-port $((9000 + i)) \
        --base local \
        --until 100 \
        --watchdog-timeout 300 &
done

wait
