#!/bin/bash

set -euox pipefail

just build_release --features until

for i in {0..5}; do
    echo "Starting node $i"

    RUST_LOG=timeboost=error,sailfish=error,timeboost_networking=error \
    ./target/release/timeboost \
        --id $i \
        --port $((8000 + i)) \
        --rpc-port $((8800 + i)) \
        --metrics-port $((9000 + i)) \
        --base local \
        --until 200 \
        --watchdog-timeout 30 \
        --late-start-node-id 0 \
        --late-start &
done

wait
