#!/usr/bin/env bash

set -emuo pipefail

cleanup() {
    trap - EXIT TERM
    kill $(jobs -p) 2>/dev/null || true
}

trap cleanup EXIT TERM INT

rounds=1000
late_start=false
keyset_file=
tps=1
stamp=
ignore_stamp=false
namespace=10101

while [[ $# -gt 0 ]]; do
    case "$1" in
        -k|--keyset-file)
            keyset_file="$2"
            shift 2
            ;;
        -l|--late)
            late_start=true
            shift
            ;;
        -n|--namespace)
            namespace="$2"
            shift 2
            ;;
        -r|--rounds)
            rounds="$2"
            shift 2
            ;;
        -t|--tps)
            tps="$2"
            shift 2
            ;;
        -s|--stamp)
            stamp="$2"
            shift 2
            ;;
        --ignore-stamp)
            ignore_stamp=true
            shift
            ;;
        *)
            echo -e "Unknown: $1\n"
            echo "Usage: $0 [Options] where

Options:

    -l | --late
        Delayed startup of first node.

    -n | --namespace <NUMBER>
        Espresso transactions namespace ID.

    -k | --keyset-file <PATH>
        Use a JSON file for node keys.

    -r | --rounds <NUMBER>
        Run for the given number of rounds (default = 1000).

    -t | --tps <NUMBER>
        Number of transactions per second to generate.

    -s | --stamp <PATH prefix>
        Path prefix for the stamp files.

    --ignore-stamp
        Ignore an existing stamp file and start from genesis"
            exit 1
            ;;
    esac
done

if [ ! $stamp ]; then
    echo "Missing -s | --stamp <PATH prefix>"
    exit 1
fi

if [ ! $keyset_file ]; then
    echo "Missing -k | --keyset-file <PATH>"
    exit 1
fi

just build_release --features="until"

nodes=$(jq '.keyset | length' $keyset_file)

pids=()
for (( i=0; i<$nodes; i++ )); do
    cmd=(target/release/timeboost
        --id $i
        --http-port $((8800 + $i))
        --until $rounds
        --keyset-file $keyset_file
        --stamp "${stamp}-$i.sf"
        --watchdog-timeout $rounds
        --namespace $namespace)

    if $ignore_stamp; then
        cmd+=(--ignore-stamp)
    fi

    if $late_start; then
        cmd+=(--late-start --late-start-node-id 0)
    fi

    echo "${cmd[@]}"
    "${cmd[@]}" &
    pids+=($!)
done

if [ "$tps" -gt 0 ]; then
    target/release/yapper --tps $tps --keyset-file $keyset_file &
fi

wait "${pids[@]}"
