#!/usr/bin/env bash

set -euo pipefail

nodes=5
rounds=1000
late_start=false
keyset_file="test-configs/local.json"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -k|--keyset-file)
            keyset-file="$2"
            shift 2
            ;;
        -l|--late)
            late_start=true
            shift
            ;;
        -n|--nodes)
            nodes="$2"
            shift 2
            ;;
        -r|--rounds)
            rounds="$2"
            shift 2
            ;;
        *)
            echo -e "Unknown: $1\n"
            echo "Usage: $0 [Options] where

Options:

    -l | --late
        Delayed startup of first node.

    -k | --keyfile <PATH>
        Use a JSON file for node keys (default \"test-configs/local.json\").

    -r | --rounds <NUMBER>
        Run for the given number of rounds (default = 1000).

    -n | --nodes <NUMBER>
        Run the given number of nodes (default = 5)."
            exit 1
            ;;
    esac
done

just build_release --features="until"

for (( i=0; i<$nodes; i++ )); do
    cmd=(target/release/timeboost
        --id $i
        --port $((8000 + $i))
        --rpc-port $((8800 + $i))
        --metrics-port $((9000 + $i))
        --until $rounds
        --nodes $nodes
        --keyset-file $keyset_file
        --watchdog-timeout $rounds)

    if $late_start; then
        cmd+=(--late-start --late-start-node-id 0)
    fi

    echo "${cmd[@]}"
    "${cmd[@]}" &
done

wait

