#!/usr/bin/env bash

set -euo pipefail

nodes=5
rounds=1000
late_start=false
keyset_file="test-configs/local.json"
tps=1
stamp=
ignore_stamp=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        -k|--keyset-file)
            keyset_file="$2"
            shift 2
            ;;
        -l|--late)
            late_start=true
            shift
            ;;
        -n|--nodes)
            nodes="$2"
            shift 2
            ;;
        -r|--rounds)
            rounds="$2"
            shift 2
            ;;
        -t|--tps)
            tps="$2"
            shift 2
            ;;
        -s|--stamp)
            stamp="$2"
            shift 2
            ;;
        --ignore-stamp)
            ignore_stamp=true
            shift
            ;;
        *)
            echo -e "Unknown: $1\n"
            echo "Usage: $0 [Options] where

Options:

    -l | --late
        Delayed startup of first node.

    -k | --keyset-file <PATH>
        Use a JSON file for node keys (default \"test-configs/local.json\").

    -r | --rounds <NUMBER>
        Run for the given number of rounds (default = 1000).

    -t | --tps <NUMBER>
        Number of transactions per second to generate.

    -s | --stamp <PATH prefix>
        Path prefix for the stamp files.

    -n | --nodes <NUMBER>
        Run the given number of nodes (default = 5).

    --ignore-stamp
        Ignore an existing stamp file and start from genesis"
            exit 1
            ;;
    esac
done

if [ ! $stamp ]; then
    echo "Missing -s | --stamp <PATH prefix>"
    exit 1
fi

set -a;
source .env;
set +a;

just build_release --features="until"

for (( i=0; i<$nodes; i++ )); do
    sig_priv_key="TIMEBOOST_DEMO_SIGNATURE_PRIVATE_KEY_$i"
    dec_priv_key="TIMEBOOST_DEMO_DECRYPTION_PRIVATE_KEY_$i"
    cmd=(target/release/timeboost
        --id $i
        --sailfish-addr "127.0.0.1:$((8000 + $i))"
        --decrypt-addr "127.0.0.1:$((10000 + $i))"
        --producer-addr "127.0.0.1:$((11000 + $i))"
        --rpc-port $((8800 + $i))
        --metrics-port $((9000 + $i))
        --until $rounds
        --nodes $nodes
        --keyset-file $keyset_file
        --tps $tps
        --stamp "${stamp}-$i.sf"
        --watchdog-timeout $rounds)

    if $ignore_stamp; then
        cmd+=(--ignore-stamp)
    fi

    if $late_start; then
        cmd+=(--late-start --late-start-node-id 0)
    fi

    echo "${cmd[@]}"
    TIMEBOOST_SIGNATURE_PRIVATE_KEY=${!sig_priv_key} \
    TIMEBOOST_DECRYPTION_PRIVATE_KEY=${!dec_priv_key} \
    "${cmd[@]}" &
done

wait

