[package]
name = "timeboost-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true }
alloy-contract = { workspace = true }
alloy-node-bindings = { workspace = true }
alloy-sol-types = { workspace = true }
serde.workspace = true
