id = 0
effective_timestamp = "2025-10-06T00:00:00Z"

[[members]]
signing_key = "x8R5rLeSEAy6BTDZ6ppzUHCMBsuuEigTQ1Ab7JGJRXJv"
dh_key = "Ch4kBmDpweDPT5WpeA3345981RAXn4q7JuHw9dZPW6eC"
dkg_enc_key = "79JoBYBquBQn7SrNbok7tEnB5ZUnxxhczrdepwssPSuFtTUzSxhj8tRs1frK6eaKrB"
public_address = "127.0.0.1:8000"
http_api = "127.0.0.1:8004"
internal_api = "127.0.0.1:8003"

[[members]]
signing_key = "z1y1wd941EWWeJzhbRBACs3uNbuaSVpS8vxaiEHY4xoo"
dh_key = "AmCvNNHdfZrWStxkkLCRrCSrk1BQbeQ1oYC7RRGjWzki"
dkg_enc_key = "6WgCNFZDNhf1GjEvDZjrMXxQMeAQJ2Ak1wyhqGdWedzvkSwqZdjVS95FapJWFhy3N6"
public_address = "127.0.0.1:8010"
http_api = "127.0.0.1:8014"
internal_api = "127.0.0.1:8013"

[[members]]
signing_key = "2A7G9nv7cEZo89LBs8KqhD8gYeB6iFphSGkYeoFcBFvdw"
dh_key = "CdQvXJum7X6aSisrBzKXcYjvj61hVjkXLaRPrd35NkPk"
dkg_enc_key = "5mQmEhakPa5GLUpm5zNCSc5p3WC4KA96FzEQMczufAve2roN2z7psiRRiDq3H3NSqt"
public_address = "127.0.0.1:8020"
http_api = "127.0.0.1:8024"
internal_api = "127.0.0.1:8023"

[[members]]
signing_key = "s9wANTxANjhRM1TJWtomAKHmEe2kBHJ3mXf6fbZWz4iQ"
dh_key = "gURXCPz62ftGo2wq1zZM5Zx7CiKJocfP3y9XzjbL4TY"
dkg_enc_key = "6KKsvcXE2QBTdYVtNj1A97ES8kr9CjWbEf4TJtXPJYXbfRG4MDzMBfJkHNSSgPybAx"
public_address = "127.0.0.1:8030"
http_api = "127.0.0.1:8034"
internal_api = "127.0.0.1:8033"

[[members]]
signing_key = "y3RwEehLiCoUuEGBtLWJ8Si94hJCtQtwvFoEScCrfQ3C"
dh_key = "C83cLbFnbhQjgd4NVTxQMJXA1yvnE6a2SD1hFEbetCXd"
dkg_enc_key = "7oUrDZH5rrY8M5pTLT4HtvA331PzkYaxrU4aen5gCxfHbaH58Y2FdDoXjmkjH4RYX7"
public_address = "127.0.0.1:8040"
http_api = "127.0.0.1:8044"
internal_api = "127.0.0.1:8043"
