committee = 0
stamp = "/tmp/timeboost.0.stamp"

[net.public]
address = "127.0.0.1:8000"
http-api = "127.0.0.1:8004"

[net.internal]
address = "127.0.0.1:8003"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "BUReRQjhWv1RYLRnuBRPBGxFJy1CXmH3JPNYePRCPeEa"
public = "x8R5rLeSEAy6BTDZ6ppzUHCMBsuuEigTQ1Ab7JGJRXJv"

[keys.dh]
secret = "AfJJgzG6UhbL7mbyBKjeniVCvmdkoF8XtjxAAPQt3bZD"
public = "Ch4kBmDpweDPT5WpeA3345981RAXn4q7JuHw9dZPW6eC"

[keys.dkg]
secret = "Cxq5TTdKaFk4rfnzUziTm452gLQg8pnteVu2Hd2tVFXu"
public = "79JoBYBquBQn7SrNbok7tEnB5ZUnxxhczrdepwssPSuFtTUzSxhj8tRs1frK6eaKrB"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
ws-url = "ws://127.0.0.1:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
