committee = 0
stamp = "/tmp/timeboost.2.stamp"

[net.public]
address = "127.0.0.1:8020"
http-api = "127.0.0.1:8024"

[net.internal]
address = "127.0.0.1:8023"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "7Tsf8A18BuPwTkB2y6h21BE78tsmEsRW9uDJRQuDJevD"
public = "2A7G9nv7cEZo89LBs8KqhD8gYeB6iFphSGkYeoFcBFvdw"

[keys.dh]
secret = "53oKyxEP59A2zmrtP9iBTDRCdfXLYpMrtbkewWFD2y4f"
public = "CdQvXJum7X6aSisrBzKXcYjvj61hVjkXLaRPrd35NkPk"

[keys.dkg]
secret = "BjuwAZ8UnqoP5TQwcE8WCnDZWFrsMr3i5WxxTXyjy6kT"
public = "5mQmEhakPa5GLUpm5zNCSc5p3WC4KA96FzEQMczufAve2roN2z7psiRRiDq3H3NSqt"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
ws-url = "ws://127.0.0.1:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
