committee = 0
stamp = "/tmp/timeboost.4.stamp"

[net.public]
address = "127.0.0.1:8040"
http-api = "127.0.0.1:8044"

[net.internal]
address = "127.0.0.1:8043"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "94aKi9LhMthWT5JcYZ2odFe6PhoAnWBSo93a2Sy5Stw9"
public = "y3RwEehLiCoUuEGBtLWJ8Si94hJCtQtwvFoEScCrfQ3C"

[keys.dh]
secret = "3sPSr3aCXtPEoYeQYfqVkxs78DRiy4udmrZFWRyGUoNy"
public = "C83cLbFnbhQjgd4NVTxQMJXA1yvnE6a2SD1hFEbetCXd"

[keys.dkg]
secret = "3x9KkgEB82NkGuVt8bZQok5KRrsc2KwWb2CTGiE1gRp8"
public = "7oUrDZH5rrY8M5pTLT4HtvA331PzkYaxrU4aen5gCxfHbaH58Y2FdDoXjmkjH4RYX7"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
ws-url = "ws://127.0.0.1:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
