committee = 0
stamp = "/tmp/timeboost.3.stamp"

[net.public]
address = "127.0.0.1:8030"
http-api = "127.0.0.1:8034"

[net.internal]
address = "127.0.0.1:8033"
nitro = "127.0.0.1:55000"

[keys.signing]
secret = "FeNA9hhCKSNxxyfsWHE2ucJ92ezqB1d9FruhTwRpLj83"
public = "s9wANTxANjhRM1TJWtomAKHmEe2kBHJ3mXf6fbZWz4iQ"

[keys.dh]
secret = "E7xp4DX3WxvhgfHkNgjnAgePvwxKewi3a6cR4H5aMMaN"
public = "gURXCPz62ftGo2wq1zZM5Zx7CiKJocfP3y9XzjbL4TY"

[keys.dkg]
secret = "9ACJD69bFZ5GaHfpZc5ivPMVr32qLF9oQs2FkgPLdoP5"
public = "6KKsvcXE2QBTdYVtNj1A97ES8kr9CjWbEf4TJtXPJYXbfRG4MDzMBfJkHNSSgPybAx"

[chain]
namespace = 10101

[chain.parent]
id = 31337
rpc-url = "http://127.0.0.1:8545/"
ws-url = "ws://127.0.0.1:8545/"
ibox-contract = "0xa0f3a1a4e2b2bcb7b48c8527c28098f207572ec1"
block-tag = "finalized"
key-manager-contract = "0x2bbf15bc655c4cc157b769cfcb1ea9924b9e1a35"

[espresso]
base-url = "https://query.decaf.testnet.espresso.network/v1/"
websockets-base-url = "wss://query.decaf.testnet.espresso.network/v1/"
max-transaction-size = 1048576
