[package]
name = "timeboost-types"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
blake3 = { workspace = true }
committable = { workspace = true }
multisig = { path = "../multisig" }
serde = { workspace = true }
sailfish-types = { path = "../sailfish-types" }

[dev-dependencies]
quickcheck = "1"
