on:
  push:
    branches:
      - main
    tags:
      # Match tags in the format YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  # DELETE THIS LATER
  pull_request:
    branches:
      - main
    tags:
      # Match tags in the format YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - name: Login to Github Container Repo
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Just
      run: |
        wget https://github.com/casey/just/releases/download/1.14.0/just-1.14.0-x86_64-unknown-linux-musl.tar.gz
        tar -vxf just-1.14.0-x86_64-unknown-linux-musl.tar.gz just
        sudo cp just /usr/bin/just
    - name: Set tag
      id: set-tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "TAG=$(date +%Y%m%d)" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "TAG=$(date +%Y%m%d)" >> $GITHUB_ENV
        fi
    - name: Build and push Docker image
      env:
        TAG: ${{ env.tag }}
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --tag ghcr.io/${{ github.repository }}:${TAG} \
          --push .
