on:
  push:
    branches:
      - main
    tags:
      # Match tags in the format YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: docker/setup-buildx-action@v3
    - name: Login to Github Container Repo
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set tag
      id: set-tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "TAG=$(date +%Y%m%d)" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "TAG=$(date +%Y%m%d)" >> $GITHUB_ENV
        fi
    # Need this to build containers in CI
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Build and push the images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Timeboost Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64
        file: ./docker/timeboost.Dockerfile
        tags: ghcr.io/espressosystems/timeboost:${{ env.TAG }}