name: Release

on:
  push:
    branches: [ "release-bin" ]   # temporary
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install rustfmt for nightly
        run: rustup component add --toolchain nightly rustfmt
        
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Build timeboost
        run: just build_release

      - name: Upload timeboost binary to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/timeboost
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
